/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.CorrelationDashboardAssociation;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CorrelationDashboardAssociationRecord extends UpdatableRecordImpl<CorrelationDashboardAssociationRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -685391245;

    /**
     * Setter for <code>proof.correlation_dashboard_association.CORRELATION_DASHBOARD_ASSOCIATION_ID</code>.
     */
    public void setCorrelationDashboardAssociationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.correlation_dashboard_association.CORRELATION_DASHBOARD_ASSOCIATION_ID</code>.
     */
    public Integer getCorrelationDashboardAssociationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.correlation_dashboard_association.CORRELATION_ID</code>.
     */
    public void setCorrelationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.correlation_dashboard_association.CORRELATION_ID</code>.
     */
    public Integer getCorrelationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.correlation_dashboard_association.USER_DASHBOARD_ID</code>.
     */
    public void setUserDashboardId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.correlation_dashboard_association.USER_DASHBOARD_ID</code>.
     */
    public Integer getUserDashboardId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CorrelationDashboardAssociation.CORRELATION_DASHBOARD_ASSOCIATION.CORRELATION_DASHBOARD_ASSOCIATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CorrelationDashboardAssociation.CORRELATION_DASHBOARD_ASSOCIATION.CORRELATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CorrelationDashboardAssociation.CORRELATION_DASHBOARD_ASSOCIATION.USER_DASHBOARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCorrelationDashboardAssociationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCorrelationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserDashboardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorrelationDashboardAssociationRecord value1(Integer value) {
        setCorrelationDashboardAssociationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorrelationDashboardAssociationRecord value2(Integer value) {
        setCorrelationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorrelationDashboardAssociationRecord value3(Integer value) {
        setUserDashboardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorrelationDashboardAssociationRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CorrelationDashboardAssociationRecord
     */
    public CorrelationDashboardAssociationRecord() {
        super(CorrelationDashboardAssociation.CORRELATION_DASHBOARD_ASSOCIATION);
    }

    /**
     * Create a detached, initialised CorrelationDashboardAssociationRecord
     */
    public CorrelationDashboardAssociationRecord(Integer correlationDashboardAssociationId, Integer correlationId, Integer userDashboardId) {
        super(CorrelationDashboardAssociation.CORRELATION_DASHBOARD_ASSOCIATION);

        set(0, correlationDashboardAssociationId);
        set(1, correlationId);
        set(2, userDashboardId);
    }
}
