/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.CustomSharedCalculation;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomSharedCalculationRecord extends UpdatableRecordImpl<CustomSharedCalculationRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1064805583;

    /**
     * Setter for <code>proof.custom_shared_calculation.CUSTOM_SHARED_CALCULATION_ID</code>.
     */
    public void setCustomSharedCalculationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.custom_shared_calculation.CUSTOM_SHARED_CALCULATION_ID</code>.
     */
    public Integer getCustomSharedCalculationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.custom_shared_calculation.CALCULATION_ID</code>.
     */
    public void setCalculationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.custom_shared_calculation.CALCULATION_ID</code>.
     */
    public Integer getCalculationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.custom_shared_calculation.USER_ID</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.custom_shared_calculation.USER_ID</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CustomSharedCalculation.CUSTOM_SHARED_CALCULATION.CUSTOM_SHARED_CALCULATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CustomSharedCalculation.CUSTOM_SHARED_CALCULATION.CALCULATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CustomSharedCalculation.CUSTOM_SHARED_CALCULATION.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCustomSharedCalculationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCalculationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomSharedCalculationRecord value1(Integer value) {
        setCustomSharedCalculationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomSharedCalculationRecord value2(Integer value) {
        setCalculationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomSharedCalculationRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomSharedCalculationRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomSharedCalculationRecord
     */
    public CustomSharedCalculationRecord() {
        super(CustomSharedCalculation.CUSTOM_SHARED_CALCULATION);
    }

    /**
     * Create a detached, initialised CustomSharedCalculationRecord
     */
    public CustomSharedCalculationRecord(Integer customSharedCalculationId, Integer calculationId, Integer userId) {
        super(CustomSharedCalculation.CUSTOM_SHARED_CALCULATION);

        set(0, customSharedCalculationId);
        set(1, calculationId);
        set(2, userId);
    }
}
