/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.CustomSharedKpi;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomSharedKpiRecord extends UpdatableRecordImpl<CustomSharedKpiRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -1322201940;

    /**
     * Setter for <code>proof.custom_shared_kpi.CUSTOM_SHARED_KPI_ID</code>.
     */
    public void setCustomSharedKpiId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.custom_shared_kpi.CUSTOM_SHARED_KPI_ID</code>.
     */
    public Integer getCustomSharedKpiId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.custom_shared_kpi.KPI_ID</code>.
     */
    public void setKpiId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.custom_shared_kpi.KPI_ID</code>.
     */
    public Integer getKpiId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.custom_shared_kpi.USER_ID</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.custom_shared_kpi.USER_ID</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CustomSharedKpi.CUSTOM_SHARED_KPI.CUSTOM_SHARED_KPI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CustomSharedKpi.CUSTOM_SHARED_KPI.KPI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return CustomSharedKpi.CUSTOM_SHARED_KPI.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCustomSharedKpiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getKpiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomSharedKpiRecord value1(Integer value) {
        setCustomSharedKpiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomSharedKpiRecord value2(Integer value) {
        setKpiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomSharedKpiRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CustomSharedKpiRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CustomSharedKpiRecord
     */
    public CustomSharedKpiRecord() {
        super(CustomSharedKpi.CUSTOM_SHARED_KPI);
    }

    /**
     * Create a detached, initialised CustomSharedKpiRecord
     */
    public CustomSharedKpiRecord(Integer customSharedKpiId, Integer kpiId, Integer userId) {
        super(CustomSharedKpi.CUSTOM_SHARED_KPI);

        set(0, customSharedKpiId);
        set(1, kpiId);
        set(2, userId);
    }
}
