/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.DashboardValueChain;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DashboardValueChainRecord extends UpdatableRecordImpl<DashboardValueChainRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 992519976;

    /**
     * Setter for <code>proof.dashboard_value_chain.DASHBOARD_VALUE_CHAIN_ID</code>.
     */
    public void setDashboardValueChainId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.dashboard_value_chain.DASHBOARD_VALUE_CHAIN_ID</code>.
     */
    public Integer getDashboardValueChainId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.dashboard_value_chain.USER_ID</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.dashboard_value_chain.USER_ID</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.dashboard_value_chain.USER_DASHBOARD_ID</code>.
     */
    public void setUserDashboardId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.dashboard_value_chain.USER_DASHBOARD_ID</code>.
     */
    public Integer getUserDashboardId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>proof.dashboard_value_chain.VALUE_CHAIN_ID</code>.
     */
    public void setValueChainId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>proof.dashboard_value_chain.VALUE_CHAIN_ID</code>.
     */
    public Integer getValueChainId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DashboardValueChain.DASHBOARD_VALUE_CHAIN.DASHBOARD_VALUE_CHAIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return DashboardValueChain.DASHBOARD_VALUE_CHAIN.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return DashboardValueChain.DASHBOARD_VALUE_CHAIN.USER_DASHBOARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return DashboardValueChain.DASHBOARD_VALUE_CHAIN.VALUE_CHAIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDashboardValueChainId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserDashboardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getValueChainId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DashboardValueChainRecord value1(Integer value) {
        setDashboardValueChainId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DashboardValueChainRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DashboardValueChainRecord value3(Integer value) {
        setUserDashboardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DashboardValueChainRecord value4(Integer value) {
        setValueChainId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DashboardValueChainRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DashboardValueChainRecord
     */
    public DashboardValueChainRecord() {
        super(DashboardValueChain.DASHBOARD_VALUE_CHAIN);
    }

    /**
     * Create a detached, initialised DashboardValueChainRecord
     */
    public DashboardValueChainRecord(Integer dashboardValueChainId, Integer userId, Integer userDashboardId, Integer valueChainId) {
        super(DashboardValueChain.DASHBOARD_VALUE_CHAIN);

        set(0, dashboardValueChainId);
        set(1, userId);
        set(2, userDashboardId);
        set(3, valueChainId);
    }
}
