/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.enums.DataSetTimePeriodStepTimeseriesInterval;
import org.kaddiya.reporting.sql.commons.tables.DataSetTimePeriodStep;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataSetTimePeriodStepRecord extends UpdatableRecordImpl<DataSetTimePeriodStepRecord> implements Record5<Integer, String, Timestamp, Timestamp, DataSetTimePeriodStepTimeseriesInterval> {

    private static final long serialVersionUID = -2121550046;

    /**
     * Setter for <code>proof.data_set_time_period_step.DATA_SET_TIME_PERIOD_STEP_ID</code>.
     */
    public void setDataSetTimePeriodStepId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.data_set_time_period_step.DATA_SET_TIME_PERIOD_STEP_ID</code>.
     */
    public Integer getDataSetTimePeriodStepId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.data_set_time_period_step.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.data_set_time_period_step.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>proof.data_set_time_period_step.START_DATE</code>.
     */
    public void setStartDate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.data_set_time_period_step.START_DATE</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>proof.data_set_time_period_step.END_DATE</code>.
     */
    public void setEndDate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>proof.data_set_time_period_step.END_DATE</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>proof.data_set_time_period_step.TIMESERIES_INTERVAL</code>.
     */
    public void setTimeseriesInterval(DataSetTimePeriodStepTimeseriesInterval value) {
        set(4, value);
    }

    /**
     * Getter for <code>proof.data_set_time_period_step.TIMESERIES_INTERVAL</code>.
     */
    public DataSetTimePeriodStepTimeseriesInterval getTimeseriesInterval() {
        return (DataSetTimePeriodStepTimeseriesInterval) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Timestamp, Timestamp, DataSetTimePeriodStepTimeseriesInterval> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Timestamp, Timestamp, DataSetTimePeriodStepTimeseriesInterval> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return DataSetTimePeriodStep.DATA_SET_TIME_PERIOD_STEP.DATA_SET_TIME_PERIOD_STEP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return DataSetTimePeriodStep.DATA_SET_TIME_PERIOD_STEP.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return DataSetTimePeriodStep.DATA_SET_TIME_PERIOD_STEP.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return DataSetTimePeriodStep.DATA_SET_TIME_PERIOD_STEP.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<DataSetTimePeriodStepTimeseriesInterval> field5() {
        return DataSetTimePeriodStep.DATA_SET_TIME_PERIOD_STEP.TIMESERIES_INTERVAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getDataSetTimePeriodStepId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSetTimePeriodStepTimeseriesInterval value5() {
        return getTimeseriesInterval();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSetTimePeriodStepRecord value1(Integer value) {
        setDataSetTimePeriodStepId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSetTimePeriodStepRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSetTimePeriodStepRecord value3(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSetTimePeriodStepRecord value4(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSetTimePeriodStepRecord value5(DataSetTimePeriodStepTimeseriesInterval value) {
        setTimeseriesInterval(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSetTimePeriodStepRecord values(Integer value1, String value2, Timestamp value3, Timestamp value4, DataSetTimePeriodStepTimeseriesInterval value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataSetTimePeriodStepRecord
     */
    public DataSetTimePeriodStepRecord() {
        super(DataSetTimePeriodStep.DATA_SET_TIME_PERIOD_STEP);
    }

    /**
     * Create a detached, initialised DataSetTimePeriodStepRecord
     */
    public DataSetTimePeriodStepRecord(Integer dataSetTimePeriodStepId, String name, Timestamp startDate, Timestamp endDate, DataSetTimePeriodStepTimeseriesInterval timeseriesInterval) {
        super(DataSetTimePeriodStep.DATA_SET_TIME_PERIOD_STEP);

        set(0, dataSetTimePeriodStepId);
        set(1, name);
        set(2, startDate);
        set(3, endDate);
        set(4, timeseriesInterval);
    }
}
