/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.enums.KpiCombinationTimePeriodType;
import org.kaddiya.reporting.sql.commons.tables.KpiCombinationTimePeriod;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KpiCombinationTimePeriodRecord extends UpdatableRecordImpl<KpiCombinationTimePeriodRecord> implements Record6<Integer, Integer, KpiCombinationTimePeriodType, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 286003277;

    /**
     * Setter for <code>proof.kpi_combination_time_period.KPI_COMBINATION_TIME_PERIOD_ID</code>.
     */
    public void setKpiCombinationTimePeriodId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.kpi_combination_time_period.KPI_COMBINATION_TIME_PERIOD_ID</code>.
     */
    public Integer getKpiCombinationTimePeriodId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.kpi_combination_time_period.KPI_COMBINATION_ID</code>.
     */
    public void setKpiCombinationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.kpi_combination_time_period.KPI_COMBINATION_ID</code>.
     */
    public Integer getKpiCombinationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.kpi_combination_time_period.TYPE</code>.
     */
    public void setType(KpiCombinationTimePeriodType value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.kpi_combination_time_period.TYPE</code>.
     */
    public KpiCombinationTimePeriodType getType() {
        return (KpiCombinationTimePeriodType) get(2);
    }

    /**
     * Setter for <code>proof.kpi_combination_time_period.NAME</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>proof.kpi_combination_time_period.NAME</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>proof.kpi_combination_time_period.START_DATE</code>.
     */
    public void setStartDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>proof.kpi_combination_time_period.START_DATE</code>.
     */
    public Timestamp getStartDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>proof.kpi_combination_time_period.END_DATE</code>.
     */
    public void setEndDate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>proof.kpi_combination_time_period.END_DATE</code>.
     */
    public Timestamp getEndDate() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, KpiCombinationTimePeriodType, String, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, KpiCombinationTimePeriodType, String, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return KpiCombinationTimePeriod.KPI_COMBINATION_TIME_PERIOD.KPI_COMBINATION_TIME_PERIOD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return KpiCombinationTimePeriod.KPI_COMBINATION_TIME_PERIOD.KPI_COMBINATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<KpiCombinationTimePeriodType> field3() {
        return KpiCombinationTimePeriod.KPI_COMBINATION_TIME_PERIOD.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return KpiCombinationTimePeriod.KPI_COMBINATION_TIME_PERIOD.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return KpiCombinationTimePeriod.KPI_COMBINATION_TIME_PERIOD.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return KpiCombinationTimePeriod.KPI_COMBINATION_TIME_PERIOD.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getKpiCombinationTimePeriodId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getKpiCombinationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiCombinationTimePeriodType value3() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiCombinationTimePeriodRecord value1(Integer value) {
        setKpiCombinationTimePeriodId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiCombinationTimePeriodRecord value2(Integer value) {
        setKpiCombinationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiCombinationTimePeriodRecord value3(KpiCombinationTimePeriodType value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiCombinationTimePeriodRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiCombinationTimePeriodRecord value5(Timestamp value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiCombinationTimePeriodRecord value6(Timestamp value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiCombinationTimePeriodRecord values(Integer value1, Integer value2, KpiCombinationTimePeriodType value3, String value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KpiCombinationTimePeriodRecord
     */
    public KpiCombinationTimePeriodRecord() {
        super(KpiCombinationTimePeriod.KPI_COMBINATION_TIME_PERIOD);
    }

    /**
     * Create a detached, initialised KpiCombinationTimePeriodRecord
     */
    public KpiCombinationTimePeriodRecord(Integer kpiCombinationTimePeriodId, Integer kpiCombinationId, KpiCombinationTimePeriodType type, String name, Timestamp startDate, Timestamp endDate) {
        super(KpiCombinationTimePeriod.KPI_COMBINATION_TIME_PERIOD);

        set(0, kpiCombinationTimePeriodId);
        set(1, kpiCombinationId);
        set(2, type);
        set(3, name);
        set(4, startDate);
        set(5, endDate);
    }
}
