/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.KpiCategory;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KpiCategoryRecord extends UpdatableRecordImpl<KpiCategoryRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1475404491;

    /**
     * Setter for <code>proof.kpi_category.KPI_CATEGORY_ID</code>.
     */
    public void setKpiCategoryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.kpi_category.KPI_CATEGORY_ID</code>.
     */
    public Integer getKpiCategoryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.kpi_category.KPI_ID</code>.
     */
    public void setKpiId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.kpi_category.KPI_ID</code>.
     */
    public Integer getKpiId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.kpi_category.CATEGORY_ID</code>.
     */
    public void setCategoryId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.kpi_category.CATEGORY_ID</code>.
     */
    public Integer getCategoryId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return KpiCategory.KPI_CATEGORY.KPI_CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return KpiCategory.KPI_CATEGORY.KPI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return KpiCategory.KPI_CATEGORY.CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getKpiCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getKpiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiCategoryRecord value1(Integer value) {
        setKpiCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiCategoryRecord value2(Integer value) {
        setKpiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiCategoryRecord value3(Integer value) {
        setCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiCategoryRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KpiCategoryRecord
     */
    public KpiCategoryRecord() {
        super(KpiCategory.KPI_CATEGORY);
    }

    /**
     * Create a detached, initialised KpiCategoryRecord
     */
    public KpiCategoryRecord(Integer kpiCategoryId, Integer kpiId, Integer categoryId) {
        super(KpiCategory.KPI_CATEGORY);

        set(0, kpiCategoryId);
        set(1, kpiId);
        set(2, categoryId);
    }
}
