/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.KpiData;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KpiDataRecord extends UpdatableRecordImpl<KpiDataRecord> implements Record4<Integer, Integer, Integer, Double> {

    private static final long serialVersionUID = 1524375976;

    /**
     * Setter for <code>proof.kpi_data.KPI_DATA_ID</code>.
     */
    public void setKpiDataId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.kpi_data.KPI_DATA_ID</code>.
     */
    public Integer getKpiDataId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.kpi_data.KPI_ID</code>.
     */
    public void setKpiId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.kpi_data.KPI_ID</code>.
     */
    public Integer getKpiId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.kpi_data.DATA_SET_TIME_PERIOD_STEP_ID</code>.
     */
    public void setDataSetTimePeriodStepId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.kpi_data.DATA_SET_TIME_PERIOD_STEP_ID</code>.
     */
    public Integer getDataSetTimePeriodStepId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>proof.kpi_data.KPI_VALUE</code>.
     */
    public void setKpiValue(Double value) {
        set(3, value);
    }

    /**
     * Getter for <code>proof.kpi_data.KPI_VALUE</code>.
     */
    public Double getKpiValue() {
        return (Double) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Double> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Double> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return KpiData.KPI_DATA.KPI_DATA_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return KpiData.KPI_DATA.KPI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return KpiData.KPI_DATA.DATA_SET_TIME_PERIOD_STEP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field4() {
        return KpiData.KPI_DATA.KPI_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getKpiDataId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getKpiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDataSetTimePeriodStepId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value4() {
        return getKpiValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiDataRecord value1(Integer value) {
        setKpiDataId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiDataRecord value2(Integer value) {
        setKpiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiDataRecord value3(Integer value) {
        setDataSetTimePeriodStepId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiDataRecord value4(Double value) {
        setKpiValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiDataRecord values(Integer value1, Integer value2, Integer value3, Double value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached KpiDataRecord
     */
    public KpiDataRecord() {
        super(KpiData.KPI_DATA);
    }

    /**
     * Create a detached, initialised KpiDataRecord
     */
    public KpiDataRecord(Integer kpiDataId, Integer kpiId, Integer dataSetTimePeriodStepId, Double kpiValue) {
        super(KpiData.KPI_DATA);

        set(0, kpiDataId);
        set(1, kpiId);
        set(2, dataSetTimePeriodStepId);
        set(3, kpiValue);
    }
}
