/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.OrgKpi;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgKpiRecord extends UpdatableRecordImpl<OrgKpiRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -995786395;

    /**
     * Setter for <code>proof.org_kpi.ORG_KPI_ID</code>.
     */
    public void setOrgKpiId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.org_kpi.ORG_KPI_ID</code>.
     */
    public Integer getOrgKpiId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.org_kpi.ORGANISATION_ID</code>.
     */
    public void setOrganisationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.org_kpi.ORGANISATION_ID</code>.
     */
    public Integer getOrganisationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.org_kpi.KPI_ID</code>.
     */
    public void setKpiId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.org_kpi.KPI_ID</code>.
     */
    public Integer getKpiId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrgKpi.ORG_KPI.ORG_KPI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OrgKpi.ORG_KPI.ORGANISATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return OrgKpi.ORG_KPI.KPI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOrgKpiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrganisationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getKpiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgKpiRecord value1(Integer value) {
        setOrgKpiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgKpiRecord value2(Integer value) {
        setOrganisationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgKpiRecord value3(Integer value) {
        setKpiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgKpiRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrgKpiRecord
     */
    public OrgKpiRecord() {
        super(OrgKpi.ORG_KPI);
    }

    /**
     * Create a detached, initialised OrgKpiRecord
     */
    public OrgKpiRecord(Integer orgKpiId, Integer organisationId, Integer kpiId) {
        super(OrgKpi.ORG_KPI);

        set(0, orgKpiId);
        set(1, organisationId);
        set(2, kpiId);
    }
}
