/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.enums.OrgPlanStatus;
import org.kaddiya.reporting.sql.commons.tables.OrgPlan;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgPlanRecord extends UpdatableRecordImpl<OrgPlanRecord> implements Record4<Integer, Integer, Integer, OrgPlanStatus> {

    private static final long serialVersionUID = 1073565798;

    /**
     * Setter for <code>proof.org_plan.ORG_PLAN_ID</code>.
     */
    public void setOrgPlanId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.org_plan.ORG_PLAN_ID</code>.
     */
    public Integer getOrgPlanId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.org_plan.ORGANISATION_ID</code>.
     */
    public void setOrganisationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.org_plan.ORGANISATION_ID</code>.
     */
    public Integer getOrganisationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.org_plan.SUBSCRIPTION_PLAN_ID</code>.
     */
    public void setSubscriptionPlanId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.org_plan.SUBSCRIPTION_PLAN_ID</code>.
     */
    public Integer getSubscriptionPlanId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>proof.org_plan.STATUS</code>.
     */
    public void setStatus(OrgPlanStatus value) {
        set(3, value);
    }

    /**
     * Getter for <code>proof.org_plan.STATUS</code>.
     */
    public OrgPlanStatus getStatus() {
        return (OrgPlanStatus) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, OrgPlanStatus> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, OrgPlanStatus> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrgPlan.ORG_PLAN.ORG_PLAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OrgPlan.ORG_PLAN.ORGANISATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return OrgPlan.ORG_PLAN.SUBSCRIPTION_PLAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<OrgPlanStatus> field4() {
        return OrgPlan.ORG_PLAN.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOrgPlanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrganisationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSubscriptionPlanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgPlanStatus value4() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgPlanRecord value1(Integer value) {
        setOrgPlanId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgPlanRecord value2(Integer value) {
        setOrganisationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgPlanRecord value3(Integer value) {
        setSubscriptionPlanId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgPlanRecord value4(OrgPlanStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgPlanRecord values(Integer value1, Integer value2, Integer value3, OrgPlanStatus value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrgPlanRecord
     */
    public OrgPlanRecord() {
        super(OrgPlan.ORG_PLAN);
    }

    /**
     * Create a detached, initialised OrgPlanRecord
     */
    public OrgPlanRecord(Integer orgPlanId, Integer organisationId, Integer subscriptionPlanId, OrgPlanStatus status) {
        super(OrgPlan.ORG_PLAN);

        set(0, orgPlanId);
        set(1, organisationId);
        set(2, subscriptionPlanId);
        set(3, status);
    }
}
