/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.OrgTag;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgTagRecord extends UpdatableRecordImpl<OrgTagRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = -1038535033;

    /**
     * Setter for <code>proof.org_tag.ORG_TAG_ID</code>.
     */
    public void setOrgTagId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.org_tag.ORG_TAG_ID</code>.
     */
    public Integer getOrgTagId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.org_tag.ORGANISATION_ID</code>.
     */
    public void setOrganisationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.org_tag.ORGANISATION_ID</code>.
     */
    public Integer getOrganisationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.org_tag.TAG_ID</code>.
     */
    public void setTagId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.org_tag.TAG_ID</code>.
     */
    public Integer getTagId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OrgTag.ORG_TAG.ORG_TAG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return OrgTag.ORG_TAG.ORGANISATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return OrgTag.ORG_TAG.TAG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOrgTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrganisationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTagId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgTagRecord value1(Integer value) {
        setOrgTagId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgTagRecord value2(Integer value) {
        setOrganisationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgTagRecord value3(Integer value) {
        setTagId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgTagRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrgTagRecord
     */
    public OrgTagRecord() {
        super(OrgTag.ORG_TAG);
    }

    /**
     * Create a detached, initialised OrgTagRecord
     */
    public OrgTagRecord(Integer orgTagId, Integer organisationId, Integer tagId) {
        super(OrgTag.ORG_TAG);

        set(0, orgTagId);
        set(1, organisationId);
        set(2, tagId);
    }
}
