/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.PaymentMode;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentModeRecord extends UpdatableRecordImpl<PaymentModeRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = -1523102340;

    /**
     * Setter for <code>proof.payment_mode.PAYMENT_MODE_ID</code>.
     */
    public void setPaymentModeId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.payment_mode.PAYMENT_MODE_ID</code>.
     */
    public Integer getPaymentModeId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.payment_mode.PAYMENT_MODE_NAME</code>.
     */
    public void setPaymentModeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.payment_mode.PAYMENT_MODE_NAME</code>.
     */
    public String getPaymentModeName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PaymentMode.PAYMENT_MODE.PAYMENT_MODE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return PaymentMode.PAYMENT_MODE.PAYMENT_MODE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPaymentModeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getPaymentModeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentModeRecord value1(Integer value) {
        setPaymentModeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentModeRecord value2(String value) {
        setPaymentModeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentModeRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentModeRecord
     */
    public PaymentModeRecord() {
        super(PaymentMode.PAYMENT_MODE);
    }

    /**
     * Create a detached, initialised PaymentModeRecord
     */
    public PaymentModeRecord(Integer paymentModeId, String paymentModeName) {
        super(PaymentMode.PAYMENT_MODE);

        set(0, paymentModeId);
        set(1, paymentModeName);
    }
}
