/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.enums.PaymentDetailsStatus;
import org.kaddiya.reporting.sql.commons.tables.PaymentDetails;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PaymentDetailsRecord extends UpdatableRecordImpl<PaymentDetailsRecord> implements Record6<Integer, Integer, Integer, Integer, Timestamp, PaymentDetailsStatus> {

    private static final long serialVersionUID = -288194139;

    /**
     * Setter for <code>proof.payment_details.PAYMENT_DETAILS_ID</code>.
     */
    public void setPaymentDetailsId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.payment_details.PAYMENT_DETAILS_ID</code>.
     */
    public Integer getPaymentDetailsId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.payment_details.PAYMENT_MODE_ID</code>.
     */
    public void setPaymentModeId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.payment_details.PAYMENT_MODE_ID</code>.
     */
    public Integer getPaymentModeId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.payment_details.ORG_PLAN_ID</code>.
     */
    public void setOrgPlanId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.payment_details.ORG_PLAN_ID</code>.
     */
    public Integer getOrgPlanId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>proof.payment_details.CREATED_BY_USER_ID</code>.
     */
    public void setCreatedByUserId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>proof.payment_details.CREATED_BY_USER_ID</code>.
     */
    public Integer getCreatedByUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>proof.payment_details.CREATED_ON</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>proof.payment_details.CREATED_ON</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>proof.payment_details.STATUS</code>.
     */
    public void setStatus(PaymentDetailsStatus value) {
        set(5, value);
    }

    /**
     * Getter for <code>proof.payment_details.STATUS</code>.
     */
    public PaymentDetailsStatus getStatus() {
        return (PaymentDetailsStatus) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Timestamp, PaymentDetailsStatus> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Timestamp, PaymentDetailsStatus> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PaymentDetails.PAYMENT_DETAILS.PAYMENT_DETAILS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PaymentDetails.PAYMENT_DETAILS.PAYMENT_MODE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PaymentDetails.PAYMENT_DETAILS.ORG_PLAN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PaymentDetails.PAYMENT_DETAILS.CREATED_BY_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return PaymentDetails.PAYMENT_DETAILS.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<PaymentDetailsStatus> field6() {
        return PaymentDetails.PAYMENT_DETAILS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPaymentDetailsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPaymentModeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOrgPlanId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCreatedByUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentDetailsStatus value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentDetailsRecord value1(Integer value) {
        setPaymentDetailsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentDetailsRecord value2(Integer value) {
        setPaymentModeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentDetailsRecord value3(Integer value) {
        setOrgPlanId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentDetailsRecord value4(Integer value) {
        setCreatedByUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentDetailsRecord value5(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentDetailsRecord value6(PaymentDetailsStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PaymentDetailsRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5, PaymentDetailsStatus value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PaymentDetailsRecord
     */
    public PaymentDetailsRecord() {
        super(PaymentDetails.PAYMENT_DETAILS);
    }

    /**
     * Create a detached, initialised PaymentDetailsRecord
     */
    public PaymentDetailsRecord(Integer paymentDetailsId, Integer paymentModeId, Integer orgPlanId, Integer createdByUserId, Timestamp createdOn, PaymentDetailsStatus status) {
        super(PaymentDetails.PAYMENT_DETAILS);

        set(0, paymentDetailsId);
        set(1, paymentModeId);
        set(2, orgPlanId);
        set(3, createdByUserId);
        set(4, createdOn);
        set(5, status);
    }
}
