/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.PerformanceCalculation;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PerformanceCalculationRecord extends UpdatableRecordImpl<PerformanceCalculationRecord> implements Record5<Integer, Integer, Integer, Integer, Date> {

    private static final long serialVersionUID = -1705207689;

    /**
     * Setter for <code>proof.performance_calculation.PERFORMANCE_CALCULATION_ID</code>.
     */
    public void setPerformanceCalculationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.performance_calculation.PERFORMANCE_CALCULATION_ID</code>.
     */
    public Integer getPerformanceCalculationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.performance_calculation.CAUSE_ID</code>.
     */
    public void setCauseId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.performance_calculation.CAUSE_ID</code>.
     */
    public Integer getCauseId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.performance_calculation.EFFECT_ID</code>.
     */
    public void setEffectId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.performance_calculation.EFFECT_ID</code>.
     */
    public Integer getEffectId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>proof.performance_calculation.CALCULATION_ID</code>.
     */
    public void setCalculationId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>proof.performance_calculation.CALCULATION_ID</code>.
     */
    public Integer getCalculationId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>proof.performance_calculation.END_DATE</code>.
     */
    public void setEndDate(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>proof.performance_calculation.END_DATE</code>.
     */
    public Date getEndDate() {
        return (Date) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Integer, Date> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Integer, Date> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return PerformanceCalculation.PERFORMANCE_CALCULATION.PERFORMANCE_CALCULATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return PerformanceCalculation.PERFORMANCE_CALCULATION.CAUSE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return PerformanceCalculation.PERFORMANCE_CALCULATION.EFFECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return PerformanceCalculation.PERFORMANCE_CALCULATION.CALCULATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return PerformanceCalculation.PERFORMANCE_CALCULATION.END_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getPerformanceCalculationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getCauseId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getEffectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCalculationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceCalculationRecord value1(Integer value) {
        setPerformanceCalculationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceCalculationRecord value2(Integer value) {
        setCauseId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceCalculationRecord value3(Integer value) {
        setEffectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceCalculationRecord value4(Integer value) {
        setCalculationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceCalculationRecord value5(Date value) {
        setEndDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PerformanceCalculationRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Date value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PerformanceCalculationRecord
     */
    public PerformanceCalculationRecord() {
        super(PerformanceCalculation.PERFORMANCE_CALCULATION);
    }

    /**
     * Create a detached, initialised PerformanceCalculationRecord
     */
    public PerformanceCalculationRecord(Integer performanceCalculationId, Integer causeId, Integer effectId, Integer calculationId, Date endDate) {
        super(PerformanceCalculation.PERFORMANCE_CALCULATION);

        set(0, performanceCalculationId);
        set(1, causeId);
        set(2, effectId);
        set(3, calculationId);
        set(4, endDate);
    }
}
