/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.RequestToAccessKpi;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RequestToAccessKpiRecord extends UpdatableRecordImpl<RequestToAccessKpiRecord> implements Record5<Integer, Integer, Integer, Integer, Timestamp> {

    private static final long serialVersionUID = 1645731982;

    /**
     * Setter for <code>proof.request_to_access_kpi.REQUEST_TO_ACCESS_KPI_ID</code>.
     */
    public void setRequestToAccessKpiId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.request_to_access_kpi.REQUEST_TO_ACCESS_KPI_ID</code>.
     */
    public Integer getRequestToAccessKpiId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.request_to_access_kpi.KPI_ID</code>.
     */
    public void setKpiId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.request_to_access_kpi.KPI_ID</code>.
     */
    public Integer getKpiId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.request_to_access_kpi.KPI_OWNER_ID</code>.
     */
    public void setKpiOwnerId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.request_to_access_kpi.KPI_OWNER_ID</code>.
     */
    public Integer getKpiOwnerId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>proof.request_to_access_kpi.REQUESTER_USER_ID</code>.
     */
    public void setRequesterUserId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>proof.request_to_access_kpi.REQUESTER_USER_ID</code>.
     */
    public Integer getRequesterUserId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>proof.request_to_access_kpi.REQUESTED_AT</code>.
     */
    public void setRequestedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>proof.request_to_access_kpi.REQUESTED_AT</code>.
     */
    public Timestamp getRequestedAt() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Integer, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, Integer, Integer, Integer, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return RequestToAccessKpi.REQUEST_TO_ACCESS_KPI.REQUEST_TO_ACCESS_KPI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return RequestToAccessKpi.REQUEST_TO_ACCESS_KPI.KPI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return RequestToAccessKpi.REQUEST_TO_ACCESS_KPI.KPI_OWNER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return RequestToAccessKpi.REQUEST_TO_ACCESS_KPI.REQUESTER_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return RequestToAccessKpi.REQUEST_TO_ACCESS_KPI.REQUESTED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getRequestToAccessKpiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getKpiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getKpiOwnerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getRequesterUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getRequestedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequestToAccessKpiRecord value1(Integer value) {
        setRequestToAccessKpiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequestToAccessKpiRecord value2(Integer value) {
        setKpiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequestToAccessKpiRecord value3(Integer value) {
        setKpiOwnerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequestToAccessKpiRecord value4(Integer value) {
        setRequesterUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequestToAccessKpiRecord value5(Timestamp value) {
        setRequestedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RequestToAccessKpiRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RequestToAccessKpiRecord
     */
    public RequestToAccessKpiRecord() {
        super(RequestToAccessKpi.REQUEST_TO_ACCESS_KPI);
    }

    /**
     * Create a detached, initialised RequestToAccessKpiRecord
     */
    public RequestToAccessKpiRecord(Integer requestToAccessKpiId, Integer kpiId, Integer kpiOwnerId, Integer requesterUserId, Timestamp requestedAt) {
        super(RequestToAccessKpi.REQUEST_TO_ACCESS_KPI);

        set(0, requestToAccessKpiId);
        set(1, kpiId);
        set(2, kpiOwnerId);
        set(3, requesterUserId);
        set(4, requestedAt);
    }
}
