/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.UserDashboardCategory;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDashboardCategoryRecord extends UpdatableRecordImpl<UserDashboardCategoryRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 420675971;

    /**
     * Setter for <code>proof.user_dashboard_category.USER_DASHBOARD_CATEGORY_ID</code>.
     */
    public void setUserDashboardCategoryId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.user_dashboard_category.USER_DASHBOARD_CATEGORY_ID</code>.
     */
    public Integer getUserDashboardCategoryId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.user_dashboard_category.USER_DASHBOARD_ID</code>.
     */
    public void setUserDashboardId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.user_dashboard_category.USER_DASHBOARD_ID</code>.
     */
    public Integer getUserDashboardId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.user_dashboard_category.CATEGORY_ID</code>.
     */
    public void setCategoryId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.user_dashboard_category.CATEGORY_ID</code>.
     */
    public Integer getCategoryId() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserDashboardCategory.USER_DASHBOARD_CATEGORY.USER_DASHBOARD_CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserDashboardCategory.USER_DASHBOARD_CATEGORY.USER_DASHBOARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserDashboardCategory.USER_DASHBOARD_CATEGORY.CATEGORY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserDashboardCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserDashboardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCategoryId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDashboardCategoryRecord value1(Integer value) {
        setUserDashboardCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDashboardCategoryRecord value2(Integer value) {
        setUserDashboardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDashboardCategoryRecord value3(Integer value) {
        setCategoryId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDashboardCategoryRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserDashboardCategoryRecord
     */
    public UserDashboardCategoryRecord() {
        super(UserDashboardCategory.USER_DASHBOARD_CATEGORY);
    }

    /**
     * Create a detached, initialised UserDashboardCategoryRecord
     */
    public UserDashboardCategoryRecord(Integer userDashboardCategoryId, Integer userDashboardId, Integer categoryId) {
        super(UserDashboardCategory.USER_DASHBOARD_CATEGORY);

        set(0, userDashboardCategoryId);
        set(1, userDashboardId);
        set(2, categoryId);
    }
}
