/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.UserDefaultDashboard;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDefaultDashboardRecord extends UpdatableRecordImpl<UserDefaultDashboardRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1544768821;

    /**
     * Setter for <code>proof.user_default_dashboard.USER_DEFAULT_DASHBOARD_ID</code>.
     */
    public void setUserDefaultDashboardId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.user_default_dashboard.USER_DEFAULT_DASHBOARD_ID</code>.
     */
    public Integer getUserDefaultDashboardId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.user_default_dashboard.USER_ID</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.user_default_dashboard.USER_ID</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.user_default_dashboard.USER_DASHBOARD_ID</code>.
     */
    public void setUserDashboardId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.user_default_dashboard.USER_DASHBOARD_ID</code>.
     */
    public Integer getUserDashboardId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>proof.user_default_dashboard.ORGANISATION_ID</code>.
     */
    public void setOrganisationId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>proof.user_default_dashboard.ORGANISATION_ID</code>.
     */
    public Integer getOrganisationId() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserDefaultDashboard.USER_DEFAULT_DASHBOARD.USER_DEFAULT_DASHBOARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserDefaultDashboard.USER_DEFAULT_DASHBOARD.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserDefaultDashboard.USER_DEFAULT_DASHBOARD.USER_DASHBOARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return UserDefaultDashboard.USER_DEFAULT_DASHBOARD.ORGANISATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserDefaultDashboardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserDashboardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getOrganisationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDefaultDashboardRecord value1(Integer value) {
        setUserDefaultDashboardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDefaultDashboardRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDefaultDashboardRecord value3(Integer value) {
        setUserDashboardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDefaultDashboardRecord value4(Integer value) {
        setOrganisationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserDefaultDashboardRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserDefaultDashboardRecord
     */
    public UserDefaultDashboardRecord() {
        super(UserDefaultDashboard.USER_DEFAULT_DASHBOARD);
    }

    /**
     * Create a detached, initialised UserDefaultDashboardRecord
     */
    public UserDefaultDashboardRecord(Integer userDefaultDashboardId, Integer userId, Integer userDashboardId, Integer organisationId) {
        super(UserDefaultDashboard.USER_DEFAULT_DASHBOARD);

        set(0, userDefaultDashboardId);
        set(1, userId);
        set(2, userDashboardId);
        set(3, organisationId);
    }
}
