/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.UserProfile;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserProfileRecord extends UpdatableRecordImpl<UserProfileRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 1865979984;

    /**
     * Setter for <code>proof.user_profile.USER_PROFILE_ID</code>.
     */
    public void setUserProfileId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.user_profile.USER_PROFILE_ID</code>.
     */
    public Integer getUserProfileId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.user_profile.USER_ID</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.user_profile.USER_ID</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.user_profile.PROFILE_IMAGE_PATH</code>.
     */
    public void setProfileImagePath(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.user_profile.PROFILE_IMAGE_PATH</code>.
     */
    public String getProfileImagePath() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserProfile.USER_PROFILE.USER_PROFILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserProfile.USER_PROFILE.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserProfile.USER_PROFILE.PROFILE_IMAGE_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getUserProfileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getProfileImagePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserProfileRecord value1(Integer value) {
        setUserProfileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserProfileRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserProfileRecord value3(String value) {
        setProfileImagePath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserProfileRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserProfileRecord
     */
    public UserProfileRecord() {
        super(UserProfile.USER_PROFILE);
    }

    /**
     * Create a detached, initialised UserProfileRecord
     */
    public UserProfileRecord(Integer userProfileId, Integer userId, String profileImagePath) {
        super(UserProfile.USER_PROFILE);

        set(0, userProfileId);
        set(1, userId);
        set(2, profileImagePath);
    }
}
