/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.tables.ValueChainElement;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValueChainElementRecord extends UpdatableRecordImpl<ValueChainElementRecord> implements Record6<Integer, Integer, Integer, String, Integer, Integer> {

    private static final long serialVersionUID = 2095408267;

    /**
     * Setter for <code>proof.value_chain_element.VALUE_CHAIN_ELEMENT_ID</code>.
     */
    public void setValueChainElementId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.value_chain_element.VALUE_CHAIN_ELEMENT_ID</code>.
     */
    public Integer getValueChainElementId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.value_chain_element.VALUE_CHAIN_ID</code>.
     */
    public void setValueChainId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.value_chain_element.VALUE_CHAIN_ID</code>.
     */
    public Integer getValueChainId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.value_chain_element.KPI_ID</code>.
     */
    public void setKpiId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.value_chain_element.KPI_ID</code>.
     */
    public Integer getKpiId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>proof.value_chain_element.TIME_SERIES</code>.
     */
    public void setTimeSeries(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>proof.value_chain_element.TIME_SERIES</code>.
     */
    public String getTimeSeries() {
        return (String) get(3);
    }

    /**
     * Setter for <code>proof.value_chain_element.X_POSITION</code>.
     */
    public void setXPosition(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>proof.value_chain_element.X_POSITION</code>.
     */
    public Integer getXPosition() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>proof.value_chain_element.Y_POSITION</code>.
     */
    public void setYPosition(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>proof.value_chain_element.Y_POSITION</code>.
     */
    public Integer getYPosition() {
        return (Integer) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, String, Integer, Integer> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, String, Integer, Integer> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ValueChainElement.VALUE_CHAIN_ELEMENT.VALUE_CHAIN_ELEMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ValueChainElement.VALUE_CHAIN_ELEMENT.VALUE_CHAIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ValueChainElement.VALUE_CHAIN_ELEMENT.KPI_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ValueChainElement.VALUE_CHAIN_ELEMENT.TIME_SERIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return ValueChainElement.VALUE_CHAIN_ELEMENT.X_POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ValueChainElement.VALUE_CHAIN_ELEMENT.Y_POSITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getValueChainElementId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getValueChainId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getKpiId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getTimeSeries();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getXPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getYPosition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainElementRecord value1(Integer value) {
        setValueChainElementId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainElementRecord value2(Integer value) {
        setValueChainId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainElementRecord value3(Integer value) {
        setKpiId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainElementRecord value4(String value) {
        setTimeSeries(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainElementRecord value5(Integer value) {
        setXPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainElementRecord value6(Integer value) {
        setYPosition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainElementRecord values(Integer value1, Integer value2, Integer value3, String value4, Integer value5, Integer value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ValueChainElementRecord
     */
    public ValueChainElementRecord() {
        super(ValueChainElement.VALUE_CHAIN_ELEMENT);
    }

    /**
     * Create a detached, initialised ValueChainElementRecord
     */
    public ValueChainElementRecord(Integer valueChainElementId, Integer valueChainId, Integer kpiId, String timeSeries, Integer xPosition, Integer yPosition) {
        super(ValueChainElement.VALUE_CHAIN_ELEMENT);

        set(0, valueChainElementId);
        set(1, valueChainId);
        set(2, kpiId);
        set(3, timeSeries);
        set(4, xPosition);
        set(5, yPosition);
    }
}
