/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.enums.ValueChainStatus;
import org.kaddiya.reporting.sql.commons.tables.ValueChain;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValueChainRecord extends UpdatableRecordImpl<ValueChainRecord> implements Record10<Integer, String, Integer, String, Date, Integer, Integer, Integer, Integer, ValueChainStatus> {

    private static final long serialVersionUID = -1918974785;

    /**
     * Setter for <code>proof.value_chain.VALUE_CHAIN_ID</code>.
     */
    public void setValueChainId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.value_chain.VALUE_CHAIN_ID</code>.
     */
    public Integer getValueChainId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.value_chain.TITLE</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.value_chain.TITLE</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>proof.value_chain.USER_ID</code>.
     */
    public void setUserId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.value_chain.USER_ID</code>.
     */
    public Integer getUserId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>proof.value_chain.START_TIME_SERIES</code>.
     */
    public void setStartTimeSeries(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>proof.value_chain.START_TIME_SERIES</code>.
     */
    public String getStartTimeSeries() {
        return (String) get(3);
    }

    /**
     * Setter for <code>proof.value_chain.START_DATE</code>.
     */
    public void setStartDate(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>proof.value_chain.START_DATE</code>.
     */
    public Date getStartDate() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>proof.value_chain.MAX_X</code>.
     */
    public void setMaxX(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>proof.value_chain.MAX_X</code>.
     */
    public Integer getMaxX() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>proof.value_chain.MAX_Y</code>.
     */
    public void setMaxY(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>proof.value_chain.MAX_Y</code>.
     */
    public Integer getMaxY() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>proof.value_chain.MIN_X</code>.
     */
    public void setMinX(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>proof.value_chain.MIN_X</code>.
     */
    public Integer getMinX() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>proof.value_chain.MIN_Y</code>.
     */
    public void setMinY(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>proof.value_chain.MIN_Y</code>.
     */
    public Integer getMinY() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>proof.value_chain.STATUS</code>.
     */
    public void setStatus(ValueChainStatus value) {
        set(9, value);
    }

    /**
     * Getter for <code>proof.value_chain.STATUS</code>.
     */
    public ValueChainStatus getStatus() {
        return (ValueChainStatus) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Integer, String, Date, Integer, Integer, Integer, Integer, ValueChainStatus> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Integer, String, Date, Integer, Integer, Integer, Integer, ValueChainStatus> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ValueChain.VALUE_CHAIN.VALUE_CHAIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return ValueChain.VALUE_CHAIN.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return ValueChain.VALUE_CHAIN.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ValueChain.VALUE_CHAIN.START_TIME_SERIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return ValueChain.VALUE_CHAIN.START_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return ValueChain.VALUE_CHAIN.MAX_X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return ValueChain.VALUE_CHAIN.MAX_Y;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return ValueChain.VALUE_CHAIN.MIN_X;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return ValueChain.VALUE_CHAIN.MIN_Y;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ValueChainStatus> field10() {
        return ValueChain.VALUE_CHAIN.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getValueChainId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStartTimeSeries();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getMaxX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getMaxY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getMinX();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getMinY();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainStatus value10() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainRecord value1(Integer value) {
        setValueChainId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainRecord value3(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainRecord value4(String value) {
        setStartTimeSeries(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainRecord value5(Date value) {
        setStartDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainRecord value6(Integer value) {
        setMaxX(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainRecord value7(Integer value) {
        setMaxY(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainRecord value8(Integer value) {
        setMinX(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainRecord value9(Integer value) {
        setMinY(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainRecord value10(ValueChainStatus value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ValueChainRecord values(Integer value1, String value2, Integer value3, String value4, Date value5, Integer value6, Integer value7, Integer value8, Integer value9, ValueChainStatus value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ValueChainRecord
     */
    public ValueChainRecord() {
        super(ValueChain.VALUE_CHAIN);
    }

    /**
     * Create a detached, initialised ValueChainRecord
     */
    public ValueChainRecord(Integer valueChainId, String title, Integer userId, String startTimeSeries, Date startDate, Integer maxX, Integer maxY, Integer minX, Integer minY, ValueChainStatus status) {
        super(ValueChain.VALUE_CHAIN);

        set(0, valueChainId);
        set(1, title);
        set(2, userId);
        set(3, startTimeSeries);
        set(4, startDate);
        set(5, maxX);
        set(6, maxY);
        set(7, minX);
        set(8, minY);
        set(9, status);
    }
}
