/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.records;


import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.kaddiya.reporting.sql.commons.enums.VceOrientationOrientationType;
import org.kaddiya.reporting.sql.commons.tables.VceOrientation;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VceOrientationRecord extends UpdatableRecordImpl<VceOrientationRecord> implements Record7<Integer, Integer, Integer, VceOrientationOrientationType, String, Double, Double> {

    private static final long serialVersionUID = -905223046;

    /**
     * Setter for <code>proof.vce_orientation.VCE_ORIENTATION_ID</code>.
     */
    public void setVceOrientationId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>proof.vce_orientation.VCE_ORIENTATION_ID</code>.
     */
    public Integer getVceOrientationId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>proof.vce_orientation.VALUE_CHAIN_ID</code>.
     */
    public void setValueChainId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>proof.vce_orientation.VALUE_CHAIN_ID</code>.
     */
    public Integer getValueChainId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>proof.vce_orientation.VALUE_CHAIN_ELEMENT_ID</code>.
     */
    public void setValueChainElementId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>proof.vce_orientation.VALUE_CHAIN_ELEMENT_ID</code>.
     */
    public Integer getValueChainElementId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>proof.vce_orientation.ORIENTATION_TYPE</code>.
     */
    public void setOrientationType(VceOrientationOrientationType value) {
        set(3, value);
    }

    /**
     * Getter for <code>proof.vce_orientation.ORIENTATION_TYPE</code>.
     */
    public VceOrientationOrientationType getOrientationType() {
        return (VceOrientationOrientationType) get(3);
    }

    /**
     * Setter for <code>proof.vce_orientation.TIME_SERIES</code>.
     */
    public void setTimeSeries(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>proof.vce_orientation.TIME_SERIES</code>.
     */
    public String getTimeSeries() {
        return (String) get(4);
    }

    /**
     * Setter for <code>proof.vce_orientation.CORRELATION_STRENGTH</code>.
     */
    public void setCorrelationStrength(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>proof.vce_orientation.CORRELATION_STRENGTH</code>.
     */
    public Double getCorrelationStrength() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>proof.vce_orientation.TIME_TO_IMPACT</code>.
     */
    public void setTimeToImpact(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>proof.vce_orientation.TIME_TO_IMPACT</code>.
     */
    public Double getTimeToImpact() {
        return (Double) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, VceOrientationOrientationType, String, Double, Double> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, VceOrientationOrientationType, String, Double, Double> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return VceOrientation.VCE_ORIENTATION.VCE_ORIENTATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return VceOrientation.VCE_ORIENTATION.VALUE_CHAIN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return VceOrientation.VCE_ORIENTATION.VALUE_CHAIN_ELEMENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<VceOrientationOrientationType> field4() {
        return VceOrientation.VCE_ORIENTATION.ORIENTATION_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return VceOrientation.VCE_ORIENTATION.TIME_SERIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return VceOrientation.VCE_ORIENTATION.CORRELATION_STRENGTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return VceOrientation.VCE_ORIENTATION.TIME_TO_IMPACT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getVceOrientationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getValueChainId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getValueChainElementId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VceOrientationOrientationType value4() {
        return getOrientationType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getTimeSeries();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getCorrelationStrength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getTimeToImpact();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VceOrientationRecord value1(Integer value) {
        setVceOrientationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VceOrientationRecord value2(Integer value) {
        setValueChainId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VceOrientationRecord value3(Integer value) {
        setValueChainElementId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VceOrientationRecord value4(VceOrientationOrientationType value) {
        setOrientationType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VceOrientationRecord value5(String value) {
        setTimeSeries(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VceOrientationRecord value6(Double value) {
        setCorrelationStrength(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VceOrientationRecord value7(Double value) {
        setTimeToImpact(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VceOrientationRecord values(Integer value1, Integer value2, Integer value3, VceOrientationOrientationType value4, String value5, Double value6, Double value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached VceOrientationRecord
     */
    public VceOrientationRecord() {
        super(VceOrientation.VCE_ORIENTATION);
    }

    /**
     * Create a detached, initialised VceOrientationRecord
     */
    public VceOrientationRecord(Integer vceOrientationId, Integer valueChainId, Integer valueChainElementId, VceOrientationOrientationType orientationType, String timeSeries, Double correlationStrength, Double timeToImpact) {
        super(VceOrientation.VCE_ORIENTATION);

        set(0, vceOrientationId);
        set(1, valueChainId);
        set(2, valueChainElementId);
        set(3, orientationType);
        set(4, timeSeries);
        set(5, correlationStrength);
        set(6, timeToImpact);
    }
}
