/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CalculationType implements Serializable {

    private static final long serialVersionUID = -824384960;

    private Integer calculationTypeId;
    private String  calculationTypeName;
    private String  calculationTypeDescription;

    public CalculationType() {}

    public CalculationType(CalculationType value) {
        this.calculationTypeId = value.calculationTypeId;
        this.calculationTypeName = value.calculationTypeName;
        this.calculationTypeDescription = value.calculationTypeDescription;
    }

    public CalculationType(
        Integer calculationTypeId,
        String  calculationTypeName,
        String  calculationTypeDescription
    ) {
        this.calculationTypeId = calculationTypeId;
        this.calculationTypeName = calculationTypeName;
        this.calculationTypeDescription = calculationTypeDescription;
    }

    public Integer getCalculationTypeId() {
        return this.calculationTypeId;
    }

    public void setCalculationTypeId(Integer calculationTypeId) {
        this.calculationTypeId = calculationTypeId;
    }

    public String getCalculationTypeName() {
        return this.calculationTypeName;
    }

    public void setCalculationTypeName(String calculationTypeName) {
        this.calculationTypeName = calculationTypeName;
    }

    public String getCalculationTypeDescription() {
        return this.calculationTypeDescription;
    }

    public void setCalculationTypeDescription(String calculationTypeDescription) {
        this.calculationTypeDescription = calculationTypeDescription;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CalculationType other = (CalculationType) obj;
        if (calculationTypeId == null) {
            if (other.calculationTypeId != null)
                return false;
        }
        else if (!calculationTypeId.equals(other.calculationTypeId))
            return false;
        if (calculationTypeName == null) {
            if (other.calculationTypeName != null)
                return false;
        }
        else if (!calculationTypeName.equals(other.calculationTypeName))
            return false;
        if (calculationTypeDescription == null) {
            if (other.calculationTypeDescription != null)
                return false;
        }
        else if (!calculationTypeDescription.equals(other.calculationTypeDescription))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((calculationTypeId == null) ? 0 : calculationTypeId.hashCode());
        result = prime * result + ((calculationTypeName == null) ? 0 : calculationTypeName.hashCode());
        result = prime * result + ((calculationTypeDescription == null) ? 0 : calculationTypeDescription.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CalculationType (");

        sb.append(calculationTypeId);
        sb.append(", ").append(calculationTypeName);
        sb.append(", ").append(calculationTypeDescription);

        sb.append(")");
        return sb.toString();
    }
}
