/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomSharedCalculation implements Serializable {

    private static final long serialVersionUID = -240872103;

    private Integer customSharedCalculationId;
    private Integer calculationId;
    private Integer userId;

    public CustomSharedCalculation() {}

    public CustomSharedCalculation(CustomSharedCalculation value) {
        this.customSharedCalculationId = value.customSharedCalculationId;
        this.calculationId = value.calculationId;
        this.userId = value.userId;
    }

    public CustomSharedCalculation(
        Integer customSharedCalculationId,
        Integer calculationId,
        Integer userId
    ) {
        this.customSharedCalculationId = customSharedCalculationId;
        this.calculationId = calculationId;
        this.userId = userId;
    }

    public Integer getCustomSharedCalculationId() {
        return this.customSharedCalculationId;
    }

    public void setCustomSharedCalculationId(Integer customSharedCalculationId) {
        this.customSharedCalculationId = customSharedCalculationId;
    }

    public Integer getCalculationId() {
        return this.calculationId;
    }

    public void setCalculationId(Integer calculationId) {
        this.calculationId = calculationId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final CustomSharedCalculation other = (CustomSharedCalculation) obj;
        if (customSharedCalculationId == null) {
            if (other.customSharedCalculationId != null)
                return false;
        }
        else if (!customSharedCalculationId.equals(other.customSharedCalculationId))
            return false;
        if (calculationId == null) {
            if (other.calculationId != null)
                return false;
        }
        else if (!calculationId.equals(other.calculationId))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((customSharedCalculationId == null) ? 0 : customSharedCalculationId.hashCode());
        result = prime * result + ((calculationId == null) ? 0 : calculationId.hashCode());
        result = prime * result + ((userId == null) ? 0 : userId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CustomSharedCalculation (");

        sb.append(customSharedCalculationId);
        sb.append(", ").append(calculationId);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
