/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DashboardValueChain implements Serializable {

    private static final long serialVersionUID = 671306655;

    private Integer dashboardValueChainId;
    private Integer userId;
    private Integer userDashboardId;
    private Integer valueChainId;

    public DashboardValueChain() {}

    public DashboardValueChain(DashboardValueChain value) {
        this.dashboardValueChainId = value.dashboardValueChainId;
        this.userId = value.userId;
        this.userDashboardId = value.userDashboardId;
        this.valueChainId = value.valueChainId;
    }

    public DashboardValueChain(
        Integer dashboardValueChainId,
        Integer userId,
        Integer userDashboardId,
        Integer valueChainId
    ) {
        this.dashboardValueChainId = dashboardValueChainId;
        this.userId = userId;
        this.userDashboardId = userDashboardId;
        this.valueChainId = valueChainId;
    }

    public Integer getDashboardValueChainId() {
        return this.dashboardValueChainId;
    }

    public void setDashboardValueChainId(Integer dashboardValueChainId) {
        this.dashboardValueChainId = dashboardValueChainId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getUserDashboardId() {
        return this.userDashboardId;
    }

    public void setUserDashboardId(Integer userDashboardId) {
        this.userDashboardId = userDashboardId;
    }

    public Integer getValueChainId() {
        return this.valueChainId;
    }

    public void setValueChainId(Integer valueChainId) {
        this.valueChainId = valueChainId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final DashboardValueChain other = (DashboardValueChain) obj;
        if (dashboardValueChainId == null) {
            if (other.dashboardValueChainId != null)
                return false;
        }
        else if (!dashboardValueChainId.equals(other.dashboardValueChainId))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (userDashboardId == null) {
            if (other.userDashboardId != null)
                return false;
        }
        else if (!userDashboardId.equals(other.userDashboardId))
            return false;
        if (valueChainId == null) {
            if (other.valueChainId != null)
                return false;
        }
        else if (!valueChainId.equals(other.valueChainId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((dashboardValueChainId == null) ? 0 : dashboardValueChainId.hashCode());
        result = prime * result + ((userId == null) ? 0 : userId.hashCode());
        result = prime * result + ((userDashboardId == null) ? 0 : userDashboardId.hashCode());
        result = prime * result + ((valueChainId == null) ? 0 : valueChainId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("DashboardValueChain (");

        sb.append(dashboardValueChainId);
        sb.append(", ").append(userId);
        sb.append(", ").append(userDashboardId);
        sb.append(", ").append(valueChainId);

        sb.append(")");
        return sb.toString();
    }
}
