/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.kaddiya.reporting.sql.commons.enums.KpiVisibility;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Kpi implements Serializable {

    private static final long serialVersionUID = 1739937895;

    private Integer       kpiId;
    private Integer       dataSetId;
    private String        kpiName;
    private KpiVisibility visibility;
    private String        description;

    public Kpi() {}

    public Kpi(Kpi value) {
        this.kpiId = value.kpiId;
        this.dataSetId = value.dataSetId;
        this.kpiName = value.kpiName;
        this.visibility = value.visibility;
        this.description = value.description;
    }

    public Kpi(
        Integer       kpiId,
        Integer       dataSetId,
        String        kpiName,
        KpiVisibility visibility,
        String        description
    ) {
        this.kpiId = kpiId;
        this.dataSetId = dataSetId;
        this.kpiName = kpiName;
        this.visibility = visibility;
        this.description = description;
    }

    public Integer getKpiId() {
        return this.kpiId;
    }

    public void setKpiId(Integer kpiId) {
        this.kpiId = kpiId;
    }

    public Integer getDataSetId() {
        return this.dataSetId;
    }

    public void setDataSetId(Integer dataSetId) {
        this.dataSetId = dataSetId;
    }

    public String getKpiName() {
        return this.kpiName;
    }

    public void setKpiName(String kpiName) {
        this.kpiName = kpiName;
    }

    public KpiVisibility getVisibility() {
        return this.visibility;
    }

    public void setVisibility(KpiVisibility visibility) {
        this.visibility = visibility;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Kpi other = (Kpi) obj;
        if (kpiId == null) {
            if (other.kpiId != null)
                return false;
        }
        else if (!kpiId.equals(other.kpiId))
            return false;
        if (dataSetId == null) {
            if (other.dataSetId != null)
                return false;
        }
        else if (!dataSetId.equals(other.dataSetId))
            return false;
        if (kpiName == null) {
            if (other.kpiName != null)
                return false;
        }
        else if (!kpiName.equals(other.kpiName))
            return false;
        if (visibility == null) {
            if (other.visibility != null)
                return false;
        }
        else if (!visibility.equals(other.visibility))
            return false;
        if (description == null) {
            if (other.description != null)
                return false;
        }
        else if (!description.equals(other.description))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((kpiId == null) ? 0 : kpiId.hashCode());
        result = prime * result + ((dataSetId == null) ? 0 : dataSetId.hashCode());
        result = prime * result + ((kpiName == null) ? 0 : kpiName.hashCode());
        result = prime * result + ((visibility == null) ? 0 : visibility.hashCode());
        result = prime * result + ((description == null) ? 0 : description.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Kpi (");

        sb.append(kpiId);
        sb.append(", ").append(dataSetId);
        sb.append(", ").append(kpiName);
        sb.append(", ").append(visibility);
        sb.append(", ").append(description);

        sb.append(")");
        return sb.toString();
    }
}
