/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.kaddiya.reporting.sql.commons.enums.KpiCombinationTimePeriodType;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KpiCombinationTimePeriod implements Serializable {

    private static final long serialVersionUID = 509155963;

    private Integer                      kpiCombinationTimePeriodId;
    private Integer                      kpiCombinationId;
    private KpiCombinationTimePeriodType type;
    private String                       name;
    private Timestamp                    startDate;
    private Timestamp                    endDate;

    public KpiCombinationTimePeriod() {}

    public KpiCombinationTimePeriod(KpiCombinationTimePeriod value) {
        this.kpiCombinationTimePeriodId = value.kpiCombinationTimePeriodId;
        this.kpiCombinationId = value.kpiCombinationId;
        this.type = value.type;
        this.name = value.name;
        this.startDate = value.startDate;
        this.endDate = value.endDate;
    }

    public KpiCombinationTimePeriod(
        Integer                      kpiCombinationTimePeriodId,
        Integer                      kpiCombinationId,
        KpiCombinationTimePeriodType type,
        String                       name,
        Timestamp                    startDate,
        Timestamp                    endDate
    ) {
        this.kpiCombinationTimePeriodId = kpiCombinationTimePeriodId;
        this.kpiCombinationId = kpiCombinationId;
        this.type = type;
        this.name = name;
        this.startDate = startDate;
        this.endDate = endDate;
    }

    public Integer getKpiCombinationTimePeriodId() {
        return this.kpiCombinationTimePeriodId;
    }

    public void setKpiCombinationTimePeriodId(Integer kpiCombinationTimePeriodId) {
        this.kpiCombinationTimePeriodId = kpiCombinationTimePeriodId;
    }

    public Integer getKpiCombinationId() {
        return this.kpiCombinationId;
    }

    public void setKpiCombinationId(Integer kpiCombinationId) {
        this.kpiCombinationId = kpiCombinationId;
    }

    public KpiCombinationTimePeriodType getType() {
        return this.type;
    }

    public void setType(KpiCombinationTimePeriodType type) {
        this.type = type;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Timestamp getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Timestamp startDate) {
        this.startDate = startDate;
    }

    public Timestamp getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Timestamp endDate) {
        this.endDate = endDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final KpiCombinationTimePeriod other = (KpiCombinationTimePeriod) obj;
        if (kpiCombinationTimePeriodId == null) {
            if (other.kpiCombinationTimePeriodId != null)
                return false;
        }
        else if (!kpiCombinationTimePeriodId.equals(other.kpiCombinationTimePeriodId))
            return false;
        if (kpiCombinationId == null) {
            if (other.kpiCombinationId != null)
                return false;
        }
        else if (!kpiCombinationId.equals(other.kpiCombinationId))
            return false;
        if (type == null) {
            if (other.type != null)
                return false;
        }
        else if (!type.equals(other.type))
            return false;
        if (name == null) {
            if (other.name != null)
                return false;
        }
        else if (!name.equals(other.name))
            return false;
        if (startDate == null) {
            if (other.startDate != null)
                return false;
        }
        else if (!startDate.equals(other.startDate))
            return false;
        if (endDate == null) {
            if (other.endDate != null)
                return false;
        }
        else if (!endDate.equals(other.endDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((kpiCombinationTimePeriodId == null) ? 0 : kpiCombinationTimePeriodId.hashCode());
        result = prime * result + ((kpiCombinationId == null) ? 0 : kpiCombinationId.hashCode());
        result = prime * result + ((type == null) ? 0 : type.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        result = prime * result + ((startDate == null) ? 0 : startDate.hashCode());
        result = prime * result + ((endDate == null) ? 0 : endDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("KpiCombinationTimePeriod (");

        sb.append(kpiCombinationTimePeriodId);
        sb.append(", ").append(kpiCombinationId);
        sb.append(", ").append(type);
        sb.append(", ").append(name);
        sb.append(", ").append(startDate);
        sb.append(", ").append(endDate);

        sb.append(")");
        return sb.toString();
    }
}
