/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KpiTag implements Serializable {

    private static final long serialVersionUID = -677488240;

    private Integer kpiTagId;
    private Integer kpiId;
    private Integer tagId;

    public KpiTag() {}

    public KpiTag(KpiTag value) {
        this.kpiTagId = value.kpiTagId;
        this.kpiId = value.kpiId;
        this.tagId = value.tagId;
    }

    public KpiTag(
        Integer kpiTagId,
        Integer kpiId,
        Integer tagId
    ) {
        this.kpiTagId = kpiTagId;
        this.kpiId = kpiId;
        this.tagId = tagId;
    }

    public Integer getKpiTagId() {
        return this.kpiTagId;
    }

    public void setKpiTagId(Integer kpiTagId) {
        this.kpiTagId = kpiTagId;
    }

    public Integer getKpiId() {
        return this.kpiId;
    }

    public void setKpiId(Integer kpiId) {
        this.kpiId = kpiId;
    }

    public Integer getTagId() {
        return this.tagId;
    }

    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final KpiTag other = (KpiTag) obj;
        if (kpiTagId == null) {
            if (other.kpiTagId != null)
                return false;
        }
        else if (!kpiTagId.equals(other.kpiTagId))
            return false;
        if (kpiId == null) {
            if (other.kpiId != null)
                return false;
        }
        else if (!kpiId.equals(other.kpiId))
            return false;
        if (tagId == null) {
            if (other.tagId != null)
                return false;
        }
        else if (!tagId.equals(other.tagId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((kpiTagId == null) ? 0 : kpiTagId.hashCode());
        result = prime * result + ((kpiId == null) ? 0 : kpiId.hashCode());
        result = prime * result + ((tagId == null) ? 0 : tagId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("KpiTag (");

        sb.append(kpiTagId);
        sb.append(", ").append(kpiId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
