/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.kaddiya.reporting.sql.commons.enums.OrganisationStatus;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organisation implements Serializable {

    private static final long serialVersionUID = -125296225;

    private Integer            organisationId;
    private String             organisationName;
    private String             fiscalYearStart;
    private String             fiscalYearEnd;
    private Timestamp          createdOn;
    private OrganisationStatus status;
    private Integer            createdBy;

    public Organisation() {}

    public Organisation(Organisation value) {
        this.organisationId = value.organisationId;
        this.organisationName = value.organisationName;
        this.fiscalYearStart = value.fiscalYearStart;
        this.fiscalYearEnd = value.fiscalYearEnd;
        this.createdOn = value.createdOn;
        this.status = value.status;
        this.createdBy = value.createdBy;
    }

    public Organisation(
        Integer            organisationId,
        String             organisationName,
        String             fiscalYearStart,
        String             fiscalYearEnd,
        Timestamp          createdOn,
        OrganisationStatus status,
        Integer            createdBy
    ) {
        this.organisationId = organisationId;
        this.organisationName = organisationName;
        this.fiscalYearStart = fiscalYearStart;
        this.fiscalYearEnd = fiscalYearEnd;
        this.createdOn = createdOn;
        this.status = status;
        this.createdBy = createdBy;
    }

    public Integer getOrganisationId() {
        return this.organisationId;
    }

    public void setOrganisationId(Integer organisationId) {
        this.organisationId = organisationId;
    }

    public String getOrganisationName() {
        return this.organisationName;
    }

    public void setOrganisationName(String organisationName) {
        this.organisationName = organisationName;
    }

    public String getFiscalYearStart() {
        return this.fiscalYearStart;
    }

    public void setFiscalYearStart(String fiscalYearStart) {
        this.fiscalYearStart = fiscalYearStart;
    }

    public String getFiscalYearEnd() {
        return this.fiscalYearEnd;
    }

    public void setFiscalYearEnd(String fiscalYearEnd) {
        this.fiscalYearEnd = fiscalYearEnd;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
    }

    public OrganisationStatus getStatus() {
        return this.status;
    }

    public void setStatus(OrganisationStatus status) {
        this.status = status;
    }

    public Integer getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(Integer createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Organisation other = (Organisation) obj;
        if (organisationId == null) {
            if (other.organisationId != null)
                return false;
        }
        else if (!organisationId.equals(other.organisationId))
            return false;
        if (organisationName == null) {
            if (other.organisationName != null)
                return false;
        }
        else if (!organisationName.equals(other.organisationName))
            return false;
        if (fiscalYearStart == null) {
            if (other.fiscalYearStart != null)
                return false;
        }
        else if (!fiscalYearStart.equals(other.fiscalYearStart))
            return false;
        if (fiscalYearEnd == null) {
            if (other.fiscalYearEnd != null)
                return false;
        }
        else if (!fiscalYearEnd.equals(other.fiscalYearEnd))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (createdBy == null) {
            if (other.createdBy != null)
                return false;
        }
        else if (!createdBy.equals(other.createdBy))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((organisationId == null) ? 0 : organisationId.hashCode());
        result = prime * result + ((organisationName == null) ? 0 : organisationName.hashCode());
        result = prime * result + ((fiscalYearStart == null) ? 0 : fiscalYearStart.hashCode());
        result = prime * result + ((fiscalYearEnd == null) ? 0 : fiscalYearEnd.hashCode());
        result = prime * result + ((createdOn == null) ? 0 : createdOn.hashCode());
        result = prime * result + ((status == null) ? 0 : status.hashCode());
        result = prime * result + ((createdBy == null) ? 0 : createdBy.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Organisation (");

        sb.append(organisationId);
        sb.append(", ").append(organisationName);
        sb.append(", ").append(fiscalYearStart);
        sb.append(", ").append(fiscalYearEnd);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(status);
        sb.append(", ").append(createdBy);

        sb.append(")");
        return sb.toString();
    }
}
