/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgCategory implements Serializable {

    private static final long serialVersionUID = -1092874976;

    private Integer orgCategoryId;
    private Integer organisationId;
    private Integer categoryId;

    public OrgCategory() {}

    public OrgCategory(OrgCategory value) {
        this.orgCategoryId = value.orgCategoryId;
        this.organisationId = value.organisationId;
        this.categoryId = value.categoryId;
    }

    public OrgCategory(
        Integer orgCategoryId,
        Integer organisationId,
        Integer categoryId
    ) {
        this.orgCategoryId = orgCategoryId;
        this.organisationId = organisationId;
        this.categoryId = categoryId;
    }

    public Integer getOrgCategoryId() {
        return this.orgCategoryId;
    }

    public void setOrgCategoryId(Integer orgCategoryId) {
        this.orgCategoryId = orgCategoryId;
    }

    public Integer getOrganisationId() {
        return this.organisationId;
    }

    public void setOrganisationId(Integer organisationId) {
        this.organisationId = organisationId;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OrgCategory other = (OrgCategory) obj;
        if (orgCategoryId == null) {
            if (other.orgCategoryId != null)
                return false;
        }
        else if (!orgCategoryId.equals(other.orgCategoryId))
            return false;
        if (organisationId == null) {
            if (other.organisationId != null)
                return false;
        }
        else if (!organisationId.equals(other.organisationId))
            return false;
        if (categoryId == null) {
            if (other.categoryId != null)
                return false;
        }
        else if (!categoryId.equals(other.categoryId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((orgCategoryId == null) ? 0 : orgCategoryId.hashCode());
        result = prime * result + ((organisationId == null) ? 0 : organisationId.hashCode());
        result = prime * result + ((categoryId == null) ? 0 : categoryId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrgCategory (");

        sb.append(orgCategoryId);
        sb.append(", ").append(organisationId);
        sb.append(", ").append(categoryId);

        sb.append(")");
        return sb.toString();
    }
}
