/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgCalculation implements Serializable {

    private static final long serialVersionUID = -1084930358;

    private Integer orgCalculationId;
    private Integer organisationId;
    private Integer calculationId;

    public OrgCalculation() {}

    public OrgCalculation(OrgCalculation value) {
        this.orgCalculationId = value.orgCalculationId;
        this.organisationId = value.organisationId;
        this.calculationId = value.calculationId;
    }

    public OrgCalculation(
        Integer orgCalculationId,
        Integer organisationId,
        Integer calculationId
    ) {
        this.orgCalculationId = orgCalculationId;
        this.organisationId = organisationId;
        this.calculationId = calculationId;
    }

    public Integer getOrgCalculationId() {
        return this.orgCalculationId;
    }

    public void setOrgCalculationId(Integer orgCalculationId) {
        this.orgCalculationId = orgCalculationId;
    }

    public Integer getOrganisationId() {
        return this.organisationId;
    }

    public void setOrganisationId(Integer organisationId) {
        this.organisationId = organisationId;
    }

    public Integer getCalculationId() {
        return this.calculationId;
    }

    public void setCalculationId(Integer calculationId) {
        this.calculationId = calculationId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OrgCalculation other = (OrgCalculation) obj;
        if (orgCalculationId == null) {
            if (other.orgCalculationId != null)
                return false;
        }
        else if (!orgCalculationId.equals(other.orgCalculationId))
            return false;
        if (organisationId == null) {
            if (other.organisationId != null)
                return false;
        }
        else if (!organisationId.equals(other.organisationId))
            return false;
        if (calculationId == null) {
            if (other.calculationId != null)
                return false;
        }
        else if (!calculationId.equals(other.calculationId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((orgCalculationId == null) ? 0 : orgCalculationId.hashCode());
        result = prime * result + ((organisationId == null) ? 0 : organisationId.hashCode());
        result = prime * result + ((calculationId == null) ? 0 : calculationId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrgCalculation (");

        sb.append(orgCalculationId);
        sb.append(", ").append(organisationId);
        sb.append(", ").append(calculationId);

        sb.append(")");
        return sb.toString();
    }
}
