/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgKpiCombination implements Serializable {

    private static final long serialVersionUID = -132119250;

    private Integer orgKpiCombinationId;
    private Integer organisationId;
    private Integer kpiCombinationId;

    public OrgKpiCombination() {}

    public OrgKpiCombination(OrgKpiCombination value) {
        this.orgKpiCombinationId = value.orgKpiCombinationId;
        this.organisationId = value.organisationId;
        this.kpiCombinationId = value.kpiCombinationId;
    }

    public OrgKpiCombination(
        Integer orgKpiCombinationId,
        Integer organisationId,
        Integer kpiCombinationId
    ) {
        this.orgKpiCombinationId = orgKpiCombinationId;
        this.organisationId = organisationId;
        this.kpiCombinationId = kpiCombinationId;
    }

    public Integer getOrgKpiCombinationId() {
        return this.orgKpiCombinationId;
    }

    public void setOrgKpiCombinationId(Integer orgKpiCombinationId) {
        this.orgKpiCombinationId = orgKpiCombinationId;
    }

    public Integer getOrganisationId() {
        return this.organisationId;
    }

    public void setOrganisationId(Integer organisationId) {
        this.organisationId = organisationId;
    }

    public Integer getKpiCombinationId() {
        return this.kpiCombinationId;
    }

    public void setKpiCombinationId(Integer kpiCombinationId) {
        this.kpiCombinationId = kpiCombinationId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final OrgKpiCombination other = (OrgKpiCombination) obj;
        if (orgKpiCombinationId == null) {
            if (other.orgKpiCombinationId != null)
                return false;
        }
        else if (!orgKpiCombinationId.equals(other.orgKpiCombinationId))
            return false;
        if (organisationId == null) {
            if (other.organisationId != null)
                return false;
        }
        else if (!organisationId.equals(other.organisationId))
            return false;
        if (kpiCombinationId == null) {
            if (other.kpiCombinationId != null)
                return false;
        }
        else if (!kpiCombinationId.equals(other.kpiCombinationId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((orgKpiCombinationId == null) ? 0 : orgKpiCombinationId.hashCode());
        result = prime * result + ((organisationId == null) ? 0 : organisationId.hashCode());
        result = prime * result + ((kpiCombinationId == null) ? 0 : kpiCombinationId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("OrgKpiCombination (");

        sb.append(orgKpiCombinationId);
        sb.append(", ").append(organisationId);
        sb.append(", ").append(kpiCombinationId);

        sb.append(")");
        return sb.toString();
    }
}
