/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PerformanceCalculation implements Serializable {

    private static final long serialVersionUID = 1087546276;

    private Integer performanceCalculationId;
    private Integer causeId;
    private Integer effectId;
    private Integer calculationId;
    private Date    endDate;

    public PerformanceCalculation() {}

    public PerformanceCalculation(PerformanceCalculation value) {
        this.performanceCalculationId = value.performanceCalculationId;
        this.causeId = value.causeId;
        this.effectId = value.effectId;
        this.calculationId = value.calculationId;
        this.endDate = value.endDate;
    }

    public PerformanceCalculation(
        Integer performanceCalculationId,
        Integer causeId,
        Integer effectId,
        Integer calculationId,
        Date    endDate
    ) {
        this.performanceCalculationId = performanceCalculationId;
        this.causeId = causeId;
        this.effectId = effectId;
        this.calculationId = calculationId;
        this.endDate = endDate;
    }

    public Integer getPerformanceCalculationId() {
        return this.performanceCalculationId;
    }

    public void setPerformanceCalculationId(Integer performanceCalculationId) {
        this.performanceCalculationId = performanceCalculationId;
    }

    public Integer getCauseId() {
        return this.causeId;
    }

    public void setCauseId(Integer causeId) {
        this.causeId = causeId;
    }

    public Integer getEffectId() {
        return this.effectId;
    }

    public void setEffectId(Integer effectId) {
        this.effectId = effectId;
    }

    public Integer getCalculationId() {
        return this.calculationId;
    }

    public void setCalculationId(Integer calculationId) {
        this.calculationId = calculationId;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final PerformanceCalculation other = (PerformanceCalculation) obj;
        if (performanceCalculationId == null) {
            if (other.performanceCalculationId != null)
                return false;
        }
        else if (!performanceCalculationId.equals(other.performanceCalculationId))
            return false;
        if (causeId == null) {
            if (other.causeId != null)
                return false;
        }
        else if (!causeId.equals(other.causeId))
            return false;
        if (effectId == null) {
            if (other.effectId != null)
                return false;
        }
        else if (!effectId.equals(other.effectId))
            return false;
        if (calculationId == null) {
            if (other.calculationId != null)
                return false;
        }
        else if (!calculationId.equals(other.calculationId))
            return false;
        if (endDate == null) {
            if (other.endDate != null)
                return false;
        }
        else if (!endDate.equals(other.endDate))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((performanceCalculationId == null) ? 0 : performanceCalculationId.hashCode());
        result = prime * result + ((causeId == null) ? 0 : causeId.hashCode());
        result = prime * result + ((effectId == null) ? 0 : effectId.hashCode());
        result = prime * result + ((calculationId == null) ? 0 : calculationId.hashCode());
        result = prime * result + ((endDate == null) ? 0 : endDate.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("PerformanceCalculation (");

        sb.append(performanceCalculationId);
        sb.append(", ").append(causeId);
        sb.append(", ").append(effectId);
        sb.append(", ").append(calculationId);
        sb.append(", ").append(endDate);

        sb.append(")");
        return sb.toString();
    }
}
