/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDefaultDashboard implements Serializable {

    private static final long serialVersionUID = -791675671;

    private Integer userDefaultDashboardId;
    private Integer userId;
    private Integer userDashboardId;
    private Integer organisationId;

    public UserDefaultDashboard() {}

    public UserDefaultDashboard(UserDefaultDashboard value) {
        this.userDefaultDashboardId = value.userDefaultDashboardId;
        this.userId = value.userId;
        this.userDashboardId = value.userDashboardId;
        this.organisationId = value.organisationId;
    }

    public UserDefaultDashboard(
        Integer userDefaultDashboardId,
        Integer userId,
        Integer userDashboardId,
        Integer organisationId
    ) {
        this.userDefaultDashboardId = userDefaultDashboardId;
        this.userId = userId;
        this.userDashboardId = userDashboardId;
        this.organisationId = organisationId;
    }

    public Integer getUserDefaultDashboardId() {
        return this.userDefaultDashboardId;
    }

    public void setUserDefaultDashboardId(Integer userDefaultDashboardId) {
        this.userDefaultDashboardId = userDefaultDashboardId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getUserDashboardId() {
        return this.userDashboardId;
    }

    public void setUserDashboardId(Integer userDashboardId) {
        this.userDashboardId = userDashboardId;
    }

    public Integer getOrganisationId() {
        return this.organisationId;
    }

    public void setOrganisationId(Integer organisationId) {
        this.organisationId = organisationId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserDefaultDashboard other = (UserDefaultDashboard) obj;
        if (userDefaultDashboardId == null) {
            if (other.userDefaultDashboardId != null)
                return false;
        }
        else if (!userDefaultDashboardId.equals(other.userDefaultDashboardId))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (userDashboardId == null) {
            if (other.userDashboardId != null)
                return false;
        }
        else if (!userDashboardId.equals(other.userDashboardId))
            return false;
        if (organisationId == null) {
            if (other.organisationId != null)
                return false;
        }
        else if (!organisationId.equals(other.organisationId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((userDefaultDashboardId == null) ? 0 : userDefaultDashboardId.hashCode());
        result = prime * result + ((userId == null) ? 0 : userId.hashCode());
        result = prime * result + ((userDashboardId == null) ? 0 : userDashboardId.hashCode());
        result = prime * result + ((organisationId == null) ? 0 : organisationId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserDefaultDashboard (");

        sb.append(userDefaultDashboardId);
        sb.append(", ").append(userId);
        sb.append(", ").append(userDashboardId);
        sb.append(", ").append(organisationId);

        sb.append(")");
        return sb.toString();
    }
}
