/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.kaddiya.reporting.sql.commons.enums.UserDashboardStatus;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDashboard implements Serializable {

    private static final long serialVersionUID = -1149442524;

    private Integer             userDashboardId;
    private String              title;
    private UserDashboardStatus status;
    private Integer             ownerId;
    private Timestamp           createdAt;

    public UserDashboard() {}

    public UserDashboard(UserDashboard value) {
        this.userDashboardId = value.userDashboardId;
        this.title = value.title;
        this.status = value.status;
        this.ownerId = value.ownerId;
        this.createdAt = value.createdAt;
    }

    public UserDashboard(
        Integer             userDashboardId,
        String              title,
        UserDashboardStatus status,
        Integer             ownerId,
        Timestamp           createdAt
    ) {
        this.userDashboardId = userDashboardId;
        this.title = title;
        this.status = status;
        this.ownerId = ownerId;
        this.createdAt = createdAt;
    }

    public Integer getUserDashboardId() {
        return this.userDashboardId;
    }

    public void setUserDashboardId(Integer userDashboardId) {
        this.userDashboardId = userDashboardId;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public UserDashboardStatus getStatus() {
        return this.status;
    }

    public void setStatus(UserDashboardStatus status) {
        this.status = status;
    }

    public Integer getOwnerId() {
        return this.ownerId;
    }

    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    public Timestamp getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(Timestamp createdAt) {
        this.createdAt = createdAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserDashboard other = (UserDashboard) obj;
        if (userDashboardId == null) {
            if (other.userDashboardId != null)
                return false;
        }
        else if (!userDashboardId.equals(other.userDashboardId))
            return false;
        if (title == null) {
            if (other.title != null)
                return false;
        }
        else if (!title.equals(other.title))
            return false;
        if (status == null) {
            if (other.status != null)
                return false;
        }
        else if (!status.equals(other.status))
            return false;
        if (ownerId == null) {
            if (other.ownerId != null)
                return false;
        }
        else if (!ownerId.equals(other.ownerId))
            return false;
        if (createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!createdAt.equals(other.createdAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((userDashboardId == null) ? 0 : userDashboardId.hashCode());
        result = prime * result + ((title == null) ? 0 : title.hashCode());
        result = prime * result + ((status == null) ? 0 : status.hashCode());
        result = prime * result + ((ownerId == null) ? 0 : ownerId.hashCode());
        result = prime * result + ((createdAt == null) ? 0 : createdAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserDashboard (");

        sb.append(userDashboardId);
        sb.append(", ").append(title);
        sb.append(", ").append(status);
        sb.append(", ").append(ownerId);
        sb.append(", ").append(createdAt);

        sb.append(")");
        return sb.toString();
    }
}
