/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDashboardCategory implements Serializable {

    private static final long serialVersionUID = 1989014886;

    private Integer userDashboardCategoryId;
    private Integer userDashboardId;
    private Integer categoryId;

    public UserDashboardCategory() {}

    public UserDashboardCategory(UserDashboardCategory value) {
        this.userDashboardCategoryId = value.userDashboardCategoryId;
        this.userDashboardId = value.userDashboardId;
        this.categoryId = value.categoryId;
    }

    public UserDashboardCategory(
        Integer userDashboardCategoryId,
        Integer userDashboardId,
        Integer categoryId
    ) {
        this.userDashboardCategoryId = userDashboardCategoryId;
        this.userDashboardId = userDashboardId;
        this.categoryId = categoryId;
    }

    public Integer getUserDashboardCategoryId() {
        return this.userDashboardCategoryId;
    }

    public void setUserDashboardCategoryId(Integer userDashboardCategoryId) {
        this.userDashboardCategoryId = userDashboardCategoryId;
    }

    public Integer getUserDashboardId() {
        return this.userDashboardId;
    }

    public void setUserDashboardId(Integer userDashboardId) {
        this.userDashboardId = userDashboardId;
    }

    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserDashboardCategory other = (UserDashboardCategory) obj;
        if (userDashboardCategoryId == null) {
            if (other.userDashboardCategoryId != null)
                return false;
        }
        else if (!userDashboardCategoryId.equals(other.userDashboardCategoryId))
            return false;
        if (userDashboardId == null) {
            if (other.userDashboardId != null)
                return false;
        }
        else if (!userDashboardId.equals(other.userDashboardId))
            return false;
        if (categoryId == null) {
            if (other.categoryId != null)
                return false;
        }
        else if (!categoryId.equals(other.categoryId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((userDashboardCategoryId == null) ? 0 : userDashboardCategoryId.hashCode());
        result = prime * result + ((userDashboardId == null) ? 0 : userDashboardId.hashCode());
        result = prime * result + ((categoryId == null) ? 0 : categoryId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserDashboardCategory (");

        sb.append(userDashboardCategoryId);
        sb.append(", ").append(userDashboardId);
        sb.append(", ").append(categoryId);

        sb.append(")");
        return sb.toString();
    }
}
