/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserDashboardTag implements Serializable {

    private static final long serialVersionUID = -1384559802;

    private Integer userDashboardTagId;
    private Integer userDashboardId;
    private Integer tagId;

    public UserDashboardTag() {}

    public UserDashboardTag(UserDashboardTag value) {
        this.userDashboardTagId = value.userDashboardTagId;
        this.userDashboardId = value.userDashboardId;
        this.tagId = value.tagId;
    }

    public UserDashboardTag(
        Integer userDashboardTagId,
        Integer userDashboardId,
        Integer tagId
    ) {
        this.userDashboardTagId = userDashboardTagId;
        this.userDashboardId = userDashboardId;
        this.tagId = tagId;
    }

    public Integer getUserDashboardTagId() {
        return this.userDashboardTagId;
    }

    public void setUserDashboardTagId(Integer userDashboardTagId) {
        this.userDashboardTagId = userDashboardTagId;
    }

    public Integer getUserDashboardId() {
        return this.userDashboardId;
    }

    public void setUserDashboardId(Integer userDashboardId) {
        this.userDashboardId = userDashboardId;
    }

    public Integer getTagId() {
        return this.tagId;
    }

    public void setTagId(Integer tagId) {
        this.tagId = tagId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UserDashboardTag other = (UserDashboardTag) obj;
        if (userDashboardTagId == null) {
            if (other.userDashboardTagId != null)
                return false;
        }
        else if (!userDashboardTagId.equals(other.userDashboardTagId))
            return false;
        if (userDashboardId == null) {
            if (other.userDashboardId != null)
                return false;
        }
        else if (!userDashboardId.equals(other.userDashboardId))
            return false;
        if (tagId == null) {
            if (other.tagId != null)
                return false;
        }
        else if (!tagId.equals(other.tagId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((userDashboardTagId == null) ? 0 : userDashboardTagId.hashCode());
        result = prime * result + ((userDashboardId == null) ? 0 : userDashboardId.hashCode());
        result = prime * result + ((tagId == null) ? 0 : tagId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserDashboardTag (");

        sb.append(userDashboardTagId);
        sb.append(", ").append(userDashboardId);
        sb.append(", ").append(tagId);

        sb.append(")");
        return sb.toString();
    }
}
