/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRole implements Serializable {

    private static final long serialVersionUID = 771976957;

    private Integer usersRoleId;
    private Integer userId;
    private Integer roleId;

    public UsersRole() {}

    public UsersRole(UsersRole value) {
        this.usersRoleId = value.usersRoleId;
        this.userId = value.userId;
        this.roleId = value.roleId;
    }

    public UsersRole(
        Integer usersRoleId,
        Integer userId,
        Integer roleId
    ) {
        this.usersRoleId = usersRoleId;
        this.userId = userId;
        this.roleId = roleId;
    }

    public Integer getUsersRoleId() {
        return this.usersRoleId;
    }

    public void setUsersRoleId(Integer usersRoleId) {
        this.usersRoleId = usersRoleId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final UsersRole other = (UsersRole) obj;
        if (usersRoleId == null) {
            if (other.usersRoleId != null)
                return false;
        }
        else if (!usersRoleId.equals(other.usersRoleId))
            return false;
        if (userId == null) {
            if (other.userId != null)
                return false;
        }
        else if (!userId.equals(other.userId))
            return false;
        if (roleId == null) {
            if (other.roleId != null)
                return false;
        }
        else if (!roleId.equals(other.roleId))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((usersRoleId == null) ? 0 : usersRoleId.hashCode());
        result = prime * result + ((userId == null) ? 0 : userId.hashCode());
        result = prime * result + ((roleId == null) ? 0 : roleId.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UsersRole (");

        sb.append(usersRoleId);
        sb.append(", ").append(userId);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
