/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ValueChainElement implements Serializable {

    private static final long serialVersionUID = 473334473;

    private Integer valueChainElementId;
    private Integer valueChainId;
    private Integer kpiId;
    private String  timeSeries;
    private Integer xPosition;
    private Integer yPosition;

    public ValueChainElement() {}

    public ValueChainElement(ValueChainElement value) {
        this.valueChainElementId = value.valueChainElementId;
        this.valueChainId = value.valueChainId;
        this.kpiId = value.kpiId;
        this.timeSeries = value.timeSeries;
        this.xPosition = value.xPosition;
        this.yPosition = value.yPosition;
    }

    public ValueChainElement(
        Integer valueChainElementId,
        Integer valueChainId,
        Integer kpiId,
        String  timeSeries,
        Integer xPosition,
        Integer yPosition
    ) {
        this.valueChainElementId = valueChainElementId;
        this.valueChainId = valueChainId;
        this.kpiId = kpiId;
        this.timeSeries = timeSeries;
        this.xPosition = xPosition;
        this.yPosition = yPosition;
    }

    public Integer getValueChainElementId() {
        return this.valueChainElementId;
    }

    public void setValueChainElementId(Integer valueChainElementId) {
        this.valueChainElementId = valueChainElementId;
    }

    public Integer getValueChainId() {
        return this.valueChainId;
    }

    public void setValueChainId(Integer valueChainId) {
        this.valueChainId = valueChainId;
    }

    public Integer getKpiId() {
        return this.kpiId;
    }

    public void setKpiId(Integer kpiId) {
        this.kpiId = kpiId;
    }

    public String getTimeSeries() {
        return this.timeSeries;
    }

    public void setTimeSeries(String timeSeries) {
        this.timeSeries = timeSeries;
    }

    public Integer getXPosition() {
        return this.xPosition;
    }

    public void setXPosition(Integer xPosition) {
        this.xPosition = xPosition;
    }

    public Integer getYPosition() {
        return this.yPosition;
    }

    public void setYPosition(Integer yPosition) {
        this.yPosition = yPosition;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ValueChainElement other = (ValueChainElement) obj;
        if (valueChainElementId == null) {
            if (other.valueChainElementId != null)
                return false;
        }
        else if (!valueChainElementId.equals(other.valueChainElementId))
            return false;
        if (valueChainId == null) {
            if (other.valueChainId != null)
                return false;
        }
        else if (!valueChainId.equals(other.valueChainId))
            return false;
        if (kpiId == null) {
            if (other.kpiId != null)
                return false;
        }
        else if (!kpiId.equals(other.kpiId))
            return false;
        if (timeSeries == null) {
            if (other.timeSeries != null)
                return false;
        }
        else if (!timeSeries.equals(other.timeSeries))
            return false;
        if (xPosition == null) {
            if (other.xPosition != null)
                return false;
        }
        else if (!xPosition.equals(other.xPosition))
            return false;
        if (yPosition == null) {
            if (other.yPosition != null)
                return false;
        }
        else if (!yPosition.equals(other.yPosition))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((valueChainElementId == null) ? 0 : valueChainElementId.hashCode());
        result = prime * result + ((valueChainId == null) ? 0 : valueChainId.hashCode());
        result = prime * result + ((kpiId == null) ? 0 : kpiId.hashCode());
        result = prime * result + ((timeSeries == null) ? 0 : timeSeries.hashCode());
        result = prime * result + ((xPosition == null) ? 0 : xPosition.hashCode());
        result = prime * result + ((yPosition == null) ? 0 : yPosition.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ValueChainElement (");

        sb.append(valueChainElementId);
        sb.append(", ").append(valueChainId);
        sb.append(", ").append(kpiId);
        sb.append(", ").append(timeSeries);
        sb.append(", ").append(xPosition);
        sb.append(", ").append(yPosition);

        sb.append(")");
        return sb.toString();
    }
}
