/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;

import org.kaddiya.reporting.sql.commons.enums.VceOrientationOrientationType;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VceOrientation implements Serializable {

    private static final long serialVersionUID = 1807591036;

    private Integer                       vceOrientationId;
    private Integer                       valueChainId;
    private Integer                       valueChainElementId;
    private VceOrientationOrientationType orientationType;
    private String                        timeSeries;
    private Double                        correlationStrength;
    private Double                        timeToImpact;

    public VceOrientation() {}

    public VceOrientation(VceOrientation value) {
        this.vceOrientationId = value.vceOrientationId;
        this.valueChainId = value.valueChainId;
        this.valueChainElementId = value.valueChainElementId;
        this.orientationType = value.orientationType;
        this.timeSeries = value.timeSeries;
        this.correlationStrength = value.correlationStrength;
        this.timeToImpact = value.timeToImpact;
    }

    public VceOrientation(
        Integer                       vceOrientationId,
        Integer                       valueChainId,
        Integer                       valueChainElementId,
        VceOrientationOrientationType orientationType,
        String                        timeSeries,
        Double                        correlationStrength,
        Double                        timeToImpact
    ) {
        this.vceOrientationId = vceOrientationId;
        this.valueChainId = valueChainId;
        this.valueChainElementId = valueChainElementId;
        this.orientationType = orientationType;
        this.timeSeries = timeSeries;
        this.correlationStrength = correlationStrength;
        this.timeToImpact = timeToImpact;
    }

    public Integer getVceOrientationId() {
        return this.vceOrientationId;
    }

    public void setVceOrientationId(Integer vceOrientationId) {
        this.vceOrientationId = vceOrientationId;
    }

    public Integer getValueChainId() {
        return this.valueChainId;
    }

    public void setValueChainId(Integer valueChainId) {
        this.valueChainId = valueChainId;
    }

    public Integer getValueChainElementId() {
        return this.valueChainElementId;
    }

    public void setValueChainElementId(Integer valueChainElementId) {
        this.valueChainElementId = valueChainElementId;
    }

    public VceOrientationOrientationType getOrientationType() {
        return this.orientationType;
    }

    public void setOrientationType(VceOrientationOrientationType orientationType) {
        this.orientationType = orientationType;
    }

    public String getTimeSeries() {
        return this.timeSeries;
    }

    public void setTimeSeries(String timeSeries) {
        this.timeSeries = timeSeries;
    }

    public Double getCorrelationStrength() {
        return this.correlationStrength;
    }

    public void setCorrelationStrength(Double correlationStrength) {
        this.correlationStrength = correlationStrength;
    }

    public Double getTimeToImpact() {
        return this.timeToImpact;
    }

    public void setTimeToImpact(Double timeToImpact) {
        this.timeToImpact = timeToImpact;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final VceOrientation other = (VceOrientation) obj;
        if (vceOrientationId == null) {
            if (other.vceOrientationId != null)
                return false;
        }
        else if (!vceOrientationId.equals(other.vceOrientationId))
            return false;
        if (valueChainId == null) {
            if (other.valueChainId != null)
                return false;
        }
        else if (!valueChainId.equals(other.valueChainId))
            return false;
        if (valueChainElementId == null) {
            if (other.valueChainElementId != null)
                return false;
        }
        else if (!valueChainElementId.equals(other.valueChainElementId))
            return false;
        if (orientationType == null) {
            if (other.orientationType != null)
                return false;
        }
        else if (!orientationType.equals(other.orientationType))
            return false;
        if (timeSeries == null) {
            if (other.timeSeries != null)
                return false;
        }
        else if (!timeSeries.equals(other.timeSeries))
            return false;
        if (correlationStrength == null) {
            if (other.correlationStrength != null)
                return false;
        }
        else if (!correlationStrength.equals(other.correlationStrength))
            return false;
        if (timeToImpact == null) {
            if (other.timeToImpact != null)
                return false;
        }
        else if (!timeToImpact.equals(other.timeToImpact))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((vceOrientationId == null) ? 0 : vceOrientationId.hashCode());
        result = prime * result + ((valueChainId == null) ? 0 : valueChainId.hashCode());
        result = prime * result + ((valueChainElementId == null) ? 0 : valueChainElementId.hashCode());
        result = prime * result + ((orientationType == null) ? 0 : orientationType.hashCode());
        result = prime * result + ((timeSeries == null) ? 0 : timeSeries.hashCode());
        result = prime * result + ((correlationStrength == null) ? 0 : correlationStrength.hashCode());
        result = prime * result + ((timeToImpact == null) ? 0 : timeToImpact.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("VceOrientation (");

        sb.append(vceOrientationId);
        sb.append(", ").append(valueChainId);
        sb.append(", ").append(valueChainElementId);
        sb.append(", ").append(orientationType);
        sb.append(", ").append(timeSeries);
        sb.append(", ").append(correlationStrength);
        sb.append(", ").append(timeToImpact);

        sb.append(")");
        return sb.toString();
    }
}
