/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.kaddiya.reporting.sql.commons.tables.Calculation;
import org.kaddiya.reporting.sql.commons.tables.CalculationType;
import org.kaddiya.reporting.sql.commons.tables.Category;
import org.kaddiya.reporting.sql.commons.tables.ChequePaymentDetails;
import org.kaddiya.reporting.sql.commons.tables.CorrelationDashboardAssociation;
import org.kaddiya.reporting.sql.commons.tables.CustomSharedCalculation;
import org.kaddiya.reporting.sql.commons.tables.CustomSharedCorrelation;
import org.kaddiya.reporting.sql.commons.tables.CustomSharedKpi;
import org.kaddiya.reporting.sql.commons.tables.DashboardValueChain;
import org.kaddiya.reporting.sql.commons.tables.DataSet;
import org.kaddiya.reporting.sql.commons.tables.DataSetTimePeriodStep;
import org.kaddiya.reporting.sql.commons.tables.Databasechangelog;
import org.kaddiya.reporting.sql.commons.tables.Databasechangeloglock;
import org.kaddiya.reporting.sql.commons.tables.ImpactCalculation;
import org.kaddiya.reporting.sql.commons.tables.Kpi;
import org.kaddiya.reporting.sql.commons.tables.KpiCategory;
import org.kaddiya.reporting.sql.commons.tables.KpiCombination;
import org.kaddiya.reporting.sql.commons.tables.KpiCombinationTimePeriod;
import org.kaddiya.reporting.sql.commons.tables.KpiData;
import org.kaddiya.reporting.sql.commons.tables.KpiTag;
import org.kaddiya.reporting.sql.commons.tables.OrgCalculation;
import org.kaddiya.reporting.sql.commons.tables.OrgCategory;
import org.kaddiya.reporting.sql.commons.tables.OrgDataSet;
import org.kaddiya.reporting.sql.commons.tables.OrgKpi;
import org.kaddiya.reporting.sql.commons.tables.OrgKpiCombination;
import org.kaddiya.reporting.sql.commons.tables.OrgPlan;
import org.kaddiya.reporting.sql.commons.tables.OrgTag;
import org.kaddiya.reporting.sql.commons.tables.OrgUser;
import org.kaddiya.reporting.sql.commons.tables.OrgUserDashboard;
import org.kaddiya.reporting.sql.commons.tables.OrgUserDetails;
import org.kaddiya.reporting.sql.commons.tables.Organisation;
import org.kaddiya.reporting.sql.commons.tables.PaymentDetails;
import org.kaddiya.reporting.sql.commons.tables.PaymentMode;
import org.kaddiya.reporting.sql.commons.tables.PerformanceCalculation;
import org.kaddiya.reporting.sql.commons.tables.RequestToAccessKpi;
import org.kaddiya.reporting.sql.commons.tables.ResetPasswordRequestEntry;
import org.kaddiya.reporting.sql.commons.tables.Role;
import org.kaddiya.reporting.sql.commons.tables.SubscriptionPlan;
import org.kaddiya.reporting.sql.commons.tables.SubscriptionPlanCharges;
import org.kaddiya.reporting.sql.commons.tables.Tag;
import org.kaddiya.reporting.sql.commons.tables.User;
import org.kaddiya.reporting.sql.commons.tables.UserDashboard;
import org.kaddiya.reporting.sql.commons.tables.UserDashboardCategory;
import org.kaddiya.reporting.sql.commons.tables.UserDashboardTag;
import org.kaddiya.reporting.sql.commons.tables.UserDefaultDashboard;
import org.kaddiya.reporting.sql.commons.tables.UserProfile;
import org.kaddiya.reporting.sql.commons.tables.UsersRole;
import org.kaddiya.reporting.sql.commons.tables.ValueChain;
import org.kaddiya.reporting.sql.commons.tables.ValueChainElement;
import org.kaddiya.reporting.sql.commons.tables.VceOrientation;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Proof extends SchemaImpl {

    private static final long serialVersionUID = 1005870119;

    /**
     * The reference instance of <code>proof</code>
     */
    public static final Proof PROOF = new Proof();

    /**
     * The table <code>proof.calculation</code>.
     */
    public final Calculation CALCULATION = org.kaddiya.reporting.sql.commons.tables.Calculation.CALCULATION;

    /**
     * The table <code>proof.calculation_type</code>.
     */
    public final CalculationType CALCULATION_TYPE = org.kaddiya.reporting.sql.commons.tables.CalculationType.CALCULATION_TYPE;

    /**
     * The table <code>proof.category</code>.
     */
    public final Category CATEGORY = org.kaddiya.reporting.sql.commons.tables.Category.CATEGORY;

    /**
     * The table <code>proof.cheque_payment_details</code>.
     */
    public final ChequePaymentDetails CHEQUE_PAYMENT_DETAILS = org.kaddiya.reporting.sql.commons.tables.ChequePaymentDetails.CHEQUE_PAYMENT_DETAILS;

    /**
     * The table <code>proof.correlation_dashboard_association</code>.
     */
    public final CorrelationDashboardAssociation CORRELATION_DASHBOARD_ASSOCIATION = org.kaddiya.reporting.sql.commons.tables.CorrelationDashboardAssociation.CORRELATION_DASHBOARD_ASSOCIATION;

    /**
     * The table <code>proof.custom_shared_calculation</code>.
     */
    public final CustomSharedCalculation CUSTOM_SHARED_CALCULATION = org.kaddiya.reporting.sql.commons.tables.CustomSharedCalculation.CUSTOM_SHARED_CALCULATION;

    /**
     * The table <code>proof.custom_shared_correlation</code>.
     */
    public final CustomSharedCorrelation CUSTOM_SHARED_CORRELATION = org.kaddiya.reporting.sql.commons.tables.CustomSharedCorrelation.CUSTOM_SHARED_CORRELATION;

    /**
     * The table <code>proof.custom_shared_kpi</code>.
     */
    public final CustomSharedKpi CUSTOM_SHARED_KPI = org.kaddiya.reporting.sql.commons.tables.CustomSharedKpi.CUSTOM_SHARED_KPI;

    /**
     * The table <code>proof.dashboard_value_chain</code>.
     */
    public final DashboardValueChain DASHBOARD_VALUE_CHAIN = org.kaddiya.reporting.sql.commons.tables.DashboardValueChain.DASHBOARD_VALUE_CHAIN;

    /**
     * The table <code>proof.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = org.kaddiya.reporting.sql.commons.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>proof.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = org.kaddiya.reporting.sql.commons.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>proof.data_set</code>.
     */
    public final DataSet DATA_SET = org.kaddiya.reporting.sql.commons.tables.DataSet.DATA_SET;

    /**
     * The table <code>proof.data_set_time_period_step</code>.
     */
    public final DataSetTimePeriodStep DATA_SET_TIME_PERIOD_STEP = org.kaddiya.reporting.sql.commons.tables.DataSetTimePeriodStep.DATA_SET_TIME_PERIOD_STEP;

    /**
     * The table <code>proof.impact_calculation</code>.
     */
    public final ImpactCalculation IMPACT_CALCULATION = org.kaddiya.reporting.sql.commons.tables.ImpactCalculation.IMPACT_CALCULATION;

    /**
     * The table <code>proof.kpi</code>.
     */
    public final Kpi KPI = org.kaddiya.reporting.sql.commons.tables.Kpi.KPI;

    /**
     * The table <code>proof.kpi_category</code>.
     */
    public final KpiCategory KPI_CATEGORY = org.kaddiya.reporting.sql.commons.tables.KpiCategory.KPI_CATEGORY;

    /**
     * The table <code>proof.kpi_combination</code>.
     */
    public final KpiCombination KPI_COMBINATION = org.kaddiya.reporting.sql.commons.tables.KpiCombination.KPI_COMBINATION;

    /**
     * The table <code>proof.kpi_combination_time_period</code>.
     */
    public final KpiCombinationTimePeriod KPI_COMBINATION_TIME_PERIOD = org.kaddiya.reporting.sql.commons.tables.KpiCombinationTimePeriod.KPI_COMBINATION_TIME_PERIOD;

    /**
     * The table <code>proof.kpi_data</code>.
     */
    public final KpiData KPI_DATA = org.kaddiya.reporting.sql.commons.tables.KpiData.KPI_DATA;

    /**
     * The table <code>proof.kpi_tag</code>.
     */
    public final KpiTag KPI_TAG = org.kaddiya.reporting.sql.commons.tables.KpiTag.KPI_TAG;

    /**
     * The table <code>proof.organisation</code>.
     */
    public final Organisation ORGANISATION = org.kaddiya.reporting.sql.commons.tables.Organisation.ORGANISATION;

    /**
     * The table <code>proof.org_calculation</code>.
     */
    public final OrgCalculation ORG_CALCULATION = org.kaddiya.reporting.sql.commons.tables.OrgCalculation.ORG_CALCULATION;

    /**
     * The table <code>proof.org_category</code>.
     */
    public final OrgCategory ORG_CATEGORY = org.kaddiya.reporting.sql.commons.tables.OrgCategory.ORG_CATEGORY;

    /**
     * The table <code>proof.org_data_set</code>.
     */
    public final OrgDataSet ORG_DATA_SET = org.kaddiya.reporting.sql.commons.tables.OrgDataSet.ORG_DATA_SET;

    /**
     * The table <code>proof.org_kpi</code>.
     */
    public final OrgKpi ORG_KPI = org.kaddiya.reporting.sql.commons.tables.OrgKpi.ORG_KPI;

    /**
     * The table <code>proof.org_kpi_combination</code>.
     */
    public final OrgKpiCombination ORG_KPI_COMBINATION = org.kaddiya.reporting.sql.commons.tables.OrgKpiCombination.ORG_KPI_COMBINATION;

    /**
     * The table <code>proof.org_plan</code>.
     */
    public final OrgPlan ORG_PLAN = org.kaddiya.reporting.sql.commons.tables.OrgPlan.ORG_PLAN;

    /**
     * The table <code>proof.org_tag</code>.
     */
    public final OrgTag ORG_TAG = org.kaddiya.reporting.sql.commons.tables.OrgTag.ORG_TAG;

    /**
     * The table <code>proof.org_user</code>.
     */
    public final OrgUser ORG_USER = org.kaddiya.reporting.sql.commons.tables.OrgUser.ORG_USER;

    /**
     * The table <code>proof.org_user_dashboard</code>.
     */
    public final OrgUserDashboard ORG_USER_DASHBOARD = org.kaddiya.reporting.sql.commons.tables.OrgUserDashboard.ORG_USER_DASHBOARD;

    /**
     * The table <code>proof.org_user_details</code>.
     */
    public final OrgUserDetails ORG_USER_DETAILS = org.kaddiya.reporting.sql.commons.tables.OrgUserDetails.ORG_USER_DETAILS;

    /**
     * The table <code>proof.payment_details</code>.
     */
    public final PaymentDetails PAYMENT_DETAILS = org.kaddiya.reporting.sql.commons.tables.PaymentDetails.PAYMENT_DETAILS;

    /**
     * The table <code>proof.payment_mode</code>.
     */
    public final PaymentMode PAYMENT_MODE = org.kaddiya.reporting.sql.commons.tables.PaymentMode.PAYMENT_MODE;

    /**
     * The table <code>proof.performance_calculation</code>.
     */
    public final PerformanceCalculation PERFORMANCE_CALCULATION = org.kaddiya.reporting.sql.commons.tables.PerformanceCalculation.PERFORMANCE_CALCULATION;

    /**
     * The table <code>proof.request_to_access_kpi</code>.
     */
    public final RequestToAccessKpi REQUEST_TO_ACCESS_KPI = org.kaddiya.reporting.sql.commons.tables.RequestToAccessKpi.REQUEST_TO_ACCESS_KPI;

    /**
     * The table <code>proof.reset_password_request_entry</code>.
     */
    public final ResetPasswordRequestEntry RESET_PASSWORD_REQUEST_ENTRY = org.kaddiya.reporting.sql.commons.tables.ResetPasswordRequestEntry.RESET_PASSWORD_REQUEST_ENTRY;

    /**
     * The table <code>proof.role</code>.
     */
    public final Role ROLE = org.kaddiya.reporting.sql.commons.tables.Role.ROLE;

    /**
     * The table <code>proof.subscription_plan</code>.
     */
    public final SubscriptionPlan SUBSCRIPTION_PLAN = org.kaddiya.reporting.sql.commons.tables.SubscriptionPlan.SUBSCRIPTION_PLAN;

    /**
     * The table <code>proof.subscription_plan_charges</code>.
     */
    public final SubscriptionPlanCharges SUBSCRIPTION_PLAN_CHARGES = org.kaddiya.reporting.sql.commons.tables.SubscriptionPlanCharges.SUBSCRIPTION_PLAN_CHARGES;

    /**
     * The table <code>proof.tag</code>.
     */
    public final Tag TAG = org.kaddiya.reporting.sql.commons.tables.Tag.TAG;

    /**
     * The table <code>proof.user</code>.
     */
    public final User USER = org.kaddiya.reporting.sql.commons.tables.User.USER;

    /**
     * The table <code>proof.users_role</code>.
     */
    public final UsersRole USERS_ROLE = org.kaddiya.reporting.sql.commons.tables.UsersRole.USERS_ROLE;

    /**
     * The table <code>proof.user_dashboard</code>.
     */
    public final UserDashboard USER_DASHBOARD = org.kaddiya.reporting.sql.commons.tables.UserDashboard.USER_DASHBOARD;

    /**
     * The table <code>proof.user_dashboard_category</code>.
     */
    public final UserDashboardCategory USER_DASHBOARD_CATEGORY = org.kaddiya.reporting.sql.commons.tables.UserDashboardCategory.USER_DASHBOARD_CATEGORY;

    /**
     * The table <code>proof.user_dashboard_tag</code>.
     */
    public final UserDashboardTag USER_DASHBOARD_TAG = org.kaddiya.reporting.sql.commons.tables.UserDashboardTag.USER_DASHBOARD_TAG;

    /**
     * The table <code>proof.user_default_dashboard</code>.
     */
    public final UserDefaultDashboard USER_DEFAULT_DASHBOARD = org.kaddiya.reporting.sql.commons.tables.UserDefaultDashboard.USER_DEFAULT_DASHBOARD;

    /**
     * The table <code>proof.user_profile</code>.
     */
    public final UserProfile USER_PROFILE = org.kaddiya.reporting.sql.commons.tables.UserProfile.USER_PROFILE;

    /**
     * The table <code>proof.value_chain</code>.
     */
    public final ValueChain VALUE_CHAIN = org.kaddiya.reporting.sql.commons.tables.ValueChain.VALUE_CHAIN;

    /**
     * The table <code>proof.value_chain_element</code>.
     */
    public final ValueChainElement VALUE_CHAIN_ELEMENT = org.kaddiya.reporting.sql.commons.tables.ValueChainElement.VALUE_CHAIN_ELEMENT;

    /**
     * The table <code>proof.vce_orientation</code>.
     */
    public final VceOrientation VCE_ORIENTATION = org.kaddiya.reporting.sql.commons.tables.VceOrientation.VCE_ORIENTATION;

    /**
     * No further instances allowed
     */
    private Proof() {
        super("proof", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Calculation.CALCULATION,
            CalculationType.CALCULATION_TYPE,
            Category.CATEGORY,
            ChequePaymentDetails.CHEQUE_PAYMENT_DETAILS,
            CorrelationDashboardAssociation.CORRELATION_DASHBOARD_ASSOCIATION,
            CustomSharedCalculation.CUSTOM_SHARED_CALCULATION,
            CustomSharedCorrelation.CUSTOM_SHARED_CORRELATION,
            CustomSharedKpi.CUSTOM_SHARED_KPI,
            DashboardValueChain.DASHBOARD_VALUE_CHAIN,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            DataSet.DATA_SET,
            DataSetTimePeriodStep.DATA_SET_TIME_PERIOD_STEP,
            ImpactCalculation.IMPACT_CALCULATION,
            Kpi.KPI,
            KpiCategory.KPI_CATEGORY,
            KpiCombination.KPI_COMBINATION,
            KpiCombinationTimePeriod.KPI_COMBINATION_TIME_PERIOD,
            KpiData.KPI_DATA,
            KpiTag.KPI_TAG,
            Organisation.ORGANISATION,
            OrgCalculation.ORG_CALCULATION,
            OrgCategory.ORG_CATEGORY,
            OrgDataSet.ORG_DATA_SET,
            OrgKpi.ORG_KPI,
            OrgKpiCombination.ORG_KPI_COMBINATION,
            OrgPlan.ORG_PLAN,
            OrgTag.ORG_TAG,
            OrgUser.ORG_USER,
            OrgUserDashboard.ORG_USER_DASHBOARD,
            OrgUserDetails.ORG_USER_DETAILS,
            PaymentDetails.PAYMENT_DETAILS,
            PaymentMode.PAYMENT_MODE,
            PerformanceCalculation.PERFORMANCE_CALCULATION,
            RequestToAccessKpi.REQUEST_TO_ACCESS_KPI,
            ResetPasswordRequestEntry.RESET_PASSWORD_REQUEST_ENTRY,
            Role.ROLE,
            SubscriptionPlan.SUBSCRIPTION_PLAN,
            SubscriptionPlanCharges.SUBSCRIPTION_PLAN_CHARGES,
            Tag.TAG,
            User.USER,
            UsersRole.USERS_ROLE,
            UserDashboard.USER_DASHBOARD,
            UserDashboardCategory.USER_DASHBOARD_CATEGORY,
            UserDashboardTag.USER_DASHBOARD_TAG,
            UserDefaultDashboard.USER_DEFAULT_DASHBOARD,
            UserProfile.USER_PROFILE,
            ValueChain.VALUE_CHAIN,
            ValueChainElement.VALUE_CHAIN_ELEMENT,
            VceOrientation.VCE_ORIENTATION);
    }
}
