/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons;


import javax.annotation.Generated;

import org.kaddiya.reporting.sql.commons.tables.Calculation;
import org.kaddiya.reporting.sql.commons.tables.CalculationType;
import org.kaddiya.reporting.sql.commons.tables.Category;
import org.kaddiya.reporting.sql.commons.tables.ChequePaymentDetails;
import org.kaddiya.reporting.sql.commons.tables.CorrelationDashboardAssociation;
import org.kaddiya.reporting.sql.commons.tables.CustomSharedCalculation;
import org.kaddiya.reporting.sql.commons.tables.CustomSharedCorrelation;
import org.kaddiya.reporting.sql.commons.tables.CustomSharedKpi;
import org.kaddiya.reporting.sql.commons.tables.DashboardValueChain;
import org.kaddiya.reporting.sql.commons.tables.DataSet;
import org.kaddiya.reporting.sql.commons.tables.DataSetTimePeriodStep;
import org.kaddiya.reporting.sql.commons.tables.Databasechangelog;
import org.kaddiya.reporting.sql.commons.tables.Databasechangeloglock;
import org.kaddiya.reporting.sql.commons.tables.ImpactCalculation;
import org.kaddiya.reporting.sql.commons.tables.Kpi;
import org.kaddiya.reporting.sql.commons.tables.KpiCategory;
import org.kaddiya.reporting.sql.commons.tables.KpiCombination;
import org.kaddiya.reporting.sql.commons.tables.KpiCombinationTimePeriod;
import org.kaddiya.reporting.sql.commons.tables.KpiData;
import org.kaddiya.reporting.sql.commons.tables.KpiTag;
import org.kaddiya.reporting.sql.commons.tables.OrgCalculation;
import org.kaddiya.reporting.sql.commons.tables.OrgCategory;
import org.kaddiya.reporting.sql.commons.tables.OrgDataSet;
import org.kaddiya.reporting.sql.commons.tables.OrgKpi;
import org.kaddiya.reporting.sql.commons.tables.OrgKpiCombination;
import org.kaddiya.reporting.sql.commons.tables.OrgPlan;
import org.kaddiya.reporting.sql.commons.tables.OrgTag;
import org.kaddiya.reporting.sql.commons.tables.OrgUser;
import org.kaddiya.reporting.sql.commons.tables.OrgUserDashboard;
import org.kaddiya.reporting.sql.commons.tables.OrgUserDetails;
import org.kaddiya.reporting.sql.commons.tables.Organisation;
import org.kaddiya.reporting.sql.commons.tables.PaymentDetails;
import org.kaddiya.reporting.sql.commons.tables.PaymentMode;
import org.kaddiya.reporting.sql.commons.tables.PerformanceCalculation;
import org.kaddiya.reporting.sql.commons.tables.RequestToAccessKpi;
import org.kaddiya.reporting.sql.commons.tables.ResetPasswordRequestEntry;
import org.kaddiya.reporting.sql.commons.tables.Role;
import org.kaddiya.reporting.sql.commons.tables.SubscriptionPlan;
import org.kaddiya.reporting.sql.commons.tables.SubscriptionPlanCharges;
import org.kaddiya.reporting.sql.commons.tables.Tag;
import org.kaddiya.reporting.sql.commons.tables.User;
import org.kaddiya.reporting.sql.commons.tables.UserDashboard;
import org.kaddiya.reporting.sql.commons.tables.UserDashboardCategory;
import org.kaddiya.reporting.sql.commons.tables.UserDashboardTag;
import org.kaddiya.reporting.sql.commons.tables.UserDefaultDashboard;
import org.kaddiya.reporting.sql.commons.tables.UserProfile;
import org.kaddiya.reporting.sql.commons.tables.UsersRole;
import org.kaddiya.reporting.sql.commons.tables.ValueChain;
import org.kaddiya.reporting.sql.commons.tables.ValueChainElement;
import org.kaddiya.reporting.sql.commons.tables.VceOrientation;


/**
 * Convenience access to all tables in proof
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>proof.calculation</code>.
     */
    public static final Calculation CALCULATION = org.kaddiya.reporting.sql.commons.tables.Calculation.CALCULATION;

    /**
     * The table <code>proof.calculation_type</code>.
     */
    public static final CalculationType CALCULATION_TYPE = org.kaddiya.reporting.sql.commons.tables.CalculationType.CALCULATION_TYPE;

    /**
     * The table <code>proof.category</code>.
     */
    public static final Category CATEGORY = org.kaddiya.reporting.sql.commons.tables.Category.CATEGORY;

    /**
     * The table <code>proof.cheque_payment_details</code>.
     */
    public static final ChequePaymentDetails CHEQUE_PAYMENT_DETAILS = org.kaddiya.reporting.sql.commons.tables.ChequePaymentDetails.CHEQUE_PAYMENT_DETAILS;

    /**
     * The table <code>proof.correlation_dashboard_association</code>.
     */
    public static final CorrelationDashboardAssociation CORRELATION_DASHBOARD_ASSOCIATION = org.kaddiya.reporting.sql.commons.tables.CorrelationDashboardAssociation.CORRELATION_DASHBOARD_ASSOCIATION;

    /**
     * The table <code>proof.custom_shared_calculation</code>.
     */
    public static final CustomSharedCalculation CUSTOM_SHARED_CALCULATION = org.kaddiya.reporting.sql.commons.tables.CustomSharedCalculation.CUSTOM_SHARED_CALCULATION;

    /**
     * The table <code>proof.custom_shared_correlation</code>.
     */
    public static final CustomSharedCorrelation CUSTOM_SHARED_CORRELATION = org.kaddiya.reporting.sql.commons.tables.CustomSharedCorrelation.CUSTOM_SHARED_CORRELATION;

    /**
     * The table <code>proof.custom_shared_kpi</code>.
     */
    public static final CustomSharedKpi CUSTOM_SHARED_KPI = org.kaddiya.reporting.sql.commons.tables.CustomSharedKpi.CUSTOM_SHARED_KPI;

    /**
     * The table <code>proof.dashboard_value_chain</code>.
     */
    public static final DashboardValueChain DASHBOARD_VALUE_CHAIN = org.kaddiya.reporting.sql.commons.tables.DashboardValueChain.DASHBOARD_VALUE_CHAIN;

    /**
     * The table <code>proof.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = org.kaddiya.reporting.sql.commons.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>proof.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = org.kaddiya.reporting.sql.commons.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>proof.data_set</code>.
     */
    public static final DataSet DATA_SET = org.kaddiya.reporting.sql.commons.tables.DataSet.DATA_SET;

    /**
     * The table <code>proof.data_set_time_period_step</code>.
     */
    public static final DataSetTimePeriodStep DATA_SET_TIME_PERIOD_STEP = org.kaddiya.reporting.sql.commons.tables.DataSetTimePeriodStep.DATA_SET_TIME_PERIOD_STEP;

    /**
     * The table <code>proof.impact_calculation</code>.
     */
    public static final ImpactCalculation IMPACT_CALCULATION = org.kaddiya.reporting.sql.commons.tables.ImpactCalculation.IMPACT_CALCULATION;

    /**
     * The table <code>proof.kpi</code>.
     */
    public static final Kpi KPI = org.kaddiya.reporting.sql.commons.tables.Kpi.KPI;

    /**
     * The table <code>proof.kpi_category</code>.
     */
    public static final KpiCategory KPI_CATEGORY = org.kaddiya.reporting.sql.commons.tables.KpiCategory.KPI_CATEGORY;

    /**
     * The table <code>proof.kpi_combination</code>.
     */
    public static final KpiCombination KPI_COMBINATION = org.kaddiya.reporting.sql.commons.tables.KpiCombination.KPI_COMBINATION;

    /**
     * The table <code>proof.kpi_combination_time_period</code>.
     */
    public static final KpiCombinationTimePeriod KPI_COMBINATION_TIME_PERIOD = org.kaddiya.reporting.sql.commons.tables.KpiCombinationTimePeriod.KPI_COMBINATION_TIME_PERIOD;

    /**
     * The table <code>proof.kpi_data</code>.
     */
    public static final KpiData KPI_DATA = org.kaddiya.reporting.sql.commons.tables.KpiData.KPI_DATA;

    /**
     * The table <code>proof.kpi_tag</code>.
     */
    public static final KpiTag KPI_TAG = org.kaddiya.reporting.sql.commons.tables.KpiTag.KPI_TAG;

    /**
     * The table <code>proof.organisation</code>.
     */
    public static final Organisation ORGANISATION = org.kaddiya.reporting.sql.commons.tables.Organisation.ORGANISATION;

    /**
     * The table <code>proof.org_calculation</code>.
     */
    public static final OrgCalculation ORG_CALCULATION = org.kaddiya.reporting.sql.commons.tables.OrgCalculation.ORG_CALCULATION;

    /**
     * The table <code>proof.org_category</code>.
     */
    public static final OrgCategory ORG_CATEGORY = org.kaddiya.reporting.sql.commons.tables.OrgCategory.ORG_CATEGORY;

    /**
     * The table <code>proof.org_data_set</code>.
     */
    public static final OrgDataSet ORG_DATA_SET = org.kaddiya.reporting.sql.commons.tables.OrgDataSet.ORG_DATA_SET;

    /**
     * The table <code>proof.org_kpi</code>.
     */
    public static final OrgKpi ORG_KPI = org.kaddiya.reporting.sql.commons.tables.OrgKpi.ORG_KPI;

    /**
     * The table <code>proof.org_kpi_combination</code>.
     */
    public static final OrgKpiCombination ORG_KPI_COMBINATION = org.kaddiya.reporting.sql.commons.tables.OrgKpiCombination.ORG_KPI_COMBINATION;

    /**
     * The table <code>proof.org_plan</code>.
     */
    public static final OrgPlan ORG_PLAN = org.kaddiya.reporting.sql.commons.tables.OrgPlan.ORG_PLAN;

    /**
     * The table <code>proof.org_tag</code>.
     */
    public static final OrgTag ORG_TAG = org.kaddiya.reporting.sql.commons.tables.OrgTag.ORG_TAG;

    /**
     * The table <code>proof.org_user</code>.
     */
    public static final OrgUser ORG_USER = org.kaddiya.reporting.sql.commons.tables.OrgUser.ORG_USER;

    /**
     * The table <code>proof.org_user_dashboard</code>.
     */
    public static final OrgUserDashboard ORG_USER_DASHBOARD = org.kaddiya.reporting.sql.commons.tables.OrgUserDashboard.ORG_USER_DASHBOARD;

    /**
     * The table <code>proof.org_user_details</code>.
     */
    public static final OrgUserDetails ORG_USER_DETAILS = org.kaddiya.reporting.sql.commons.tables.OrgUserDetails.ORG_USER_DETAILS;

    /**
     * The table <code>proof.payment_details</code>.
     */
    public static final PaymentDetails PAYMENT_DETAILS = org.kaddiya.reporting.sql.commons.tables.PaymentDetails.PAYMENT_DETAILS;

    /**
     * The table <code>proof.payment_mode</code>.
     */
    public static final PaymentMode PAYMENT_MODE = org.kaddiya.reporting.sql.commons.tables.PaymentMode.PAYMENT_MODE;

    /**
     * The table <code>proof.performance_calculation</code>.
     */
    public static final PerformanceCalculation PERFORMANCE_CALCULATION = org.kaddiya.reporting.sql.commons.tables.PerformanceCalculation.PERFORMANCE_CALCULATION;

    /**
     * The table <code>proof.request_to_access_kpi</code>.
     */
    public static final RequestToAccessKpi REQUEST_TO_ACCESS_KPI = org.kaddiya.reporting.sql.commons.tables.RequestToAccessKpi.REQUEST_TO_ACCESS_KPI;

    /**
     * The table <code>proof.reset_password_request_entry</code>.
     */
    public static final ResetPasswordRequestEntry RESET_PASSWORD_REQUEST_ENTRY = org.kaddiya.reporting.sql.commons.tables.ResetPasswordRequestEntry.RESET_PASSWORD_REQUEST_ENTRY;

    /**
     * The table <code>proof.role</code>.
     */
    public static final Role ROLE = org.kaddiya.reporting.sql.commons.tables.Role.ROLE;

    /**
     * The table <code>proof.subscription_plan</code>.
     */
    public static final SubscriptionPlan SUBSCRIPTION_PLAN = org.kaddiya.reporting.sql.commons.tables.SubscriptionPlan.SUBSCRIPTION_PLAN;

    /**
     * The table <code>proof.subscription_plan_charges</code>.
     */
    public static final SubscriptionPlanCharges SUBSCRIPTION_PLAN_CHARGES = org.kaddiya.reporting.sql.commons.tables.SubscriptionPlanCharges.SUBSCRIPTION_PLAN_CHARGES;

    /**
     * The table <code>proof.tag</code>.
     */
    public static final Tag TAG = org.kaddiya.reporting.sql.commons.tables.Tag.TAG;

    /**
     * The table <code>proof.user</code>.
     */
    public static final User USER = org.kaddiya.reporting.sql.commons.tables.User.USER;

    /**
     * The table <code>proof.users_role</code>.
     */
    public static final UsersRole USERS_ROLE = org.kaddiya.reporting.sql.commons.tables.UsersRole.USERS_ROLE;

    /**
     * The table <code>proof.user_dashboard</code>.
     */
    public static final UserDashboard USER_DASHBOARD = org.kaddiya.reporting.sql.commons.tables.UserDashboard.USER_DASHBOARD;

    /**
     * The table <code>proof.user_dashboard_category</code>.
     */
    public static final UserDashboardCategory USER_DASHBOARD_CATEGORY = org.kaddiya.reporting.sql.commons.tables.UserDashboardCategory.USER_DASHBOARD_CATEGORY;

    /**
     * The table <code>proof.user_dashboard_tag</code>.
     */
    public static final UserDashboardTag USER_DASHBOARD_TAG = org.kaddiya.reporting.sql.commons.tables.UserDashboardTag.USER_DASHBOARD_TAG;

    /**
     * The table <code>proof.user_default_dashboard</code>.
     */
    public static final UserDefaultDashboard USER_DEFAULT_DASHBOARD = org.kaddiya.reporting.sql.commons.tables.UserDefaultDashboard.USER_DEFAULT_DASHBOARD;

    /**
     * The table <code>proof.user_profile</code>.
     */
    public static final UserProfile USER_PROFILE = org.kaddiya.reporting.sql.commons.tables.UserProfile.USER_PROFILE;

    /**
     * The table <code>proof.value_chain</code>.
     */
    public static final ValueChain VALUE_CHAIN = org.kaddiya.reporting.sql.commons.tables.ValueChain.VALUE_CHAIN;

    /**
     * The table <code>proof.value_chain_element</code>.
     */
    public static final ValueChainElement VALUE_CHAIN_ELEMENT = org.kaddiya.reporting.sql.commons.tables.ValueChainElement.VALUE_CHAIN_ELEMENT;

    /**
     * The table <code>proof.vce_orientation</code>.
     */
    public static final VceOrientation VCE_ORIENTATION = org.kaddiya.reporting.sql.commons.tables.VceOrientation.VCE_ORIENTATION;
}
