/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.kaddiya.reporting.sql.commons.Keys;
import org.kaddiya.reporting.sql.commons.Proof;
import org.kaddiya.reporting.sql.commons.tables.records.CorrelationDashboardAssociationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CorrelationDashboardAssociation extends TableImpl<CorrelationDashboardAssociationRecord> {

    private static final long serialVersionUID = -559423533;

    /**
     * The reference instance of <code>proof.correlation_dashboard_association</code>
     */
    public static final CorrelationDashboardAssociation CORRELATION_DASHBOARD_ASSOCIATION = new CorrelationDashboardAssociation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CorrelationDashboardAssociationRecord> getRecordType() {
        return CorrelationDashboardAssociationRecord.class;
    }

    /**
     * The column <code>proof.correlation_dashboard_association.CORRELATION_DASHBOARD_ASSOCIATION_ID</code>.
     */
    public final TableField<CorrelationDashboardAssociationRecord, Integer> CORRELATION_DASHBOARD_ASSOCIATION_ID = createField("CORRELATION_DASHBOARD_ASSOCIATION_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.correlation_dashboard_association.CORRELATION_ID</code>.
     */
    public final TableField<CorrelationDashboardAssociationRecord, Integer> CORRELATION_ID = createField("CORRELATION_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.correlation_dashboard_association.USER_DASHBOARD_ID</code>.
     */
    public final TableField<CorrelationDashboardAssociationRecord, Integer> USER_DASHBOARD_ID = createField("USER_DASHBOARD_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>proof.correlation_dashboard_association</code> table reference
     */
    public CorrelationDashboardAssociation() {
        this("correlation_dashboard_association", null);
    }

    /**
     * Create an aliased <code>proof.correlation_dashboard_association</code> table reference
     */
    public CorrelationDashboardAssociation(String alias) {
        this(alias, CORRELATION_DASHBOARD_ASSOCIATION);
    }

    private CorrelationDashboardAssociation(String alias, Table<CorrelationDashboardAssociationRecord> aliased) {
        this(alias, aliased, null);
    }

    private CorrelationDashboardAssociation(String alias, Table<CorrelationDashboardAssociationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Proof.PROOF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CorrelationDashboardAssociationRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CORRELATION_DASHBOARD_ASSOCIATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CorrelationDashboardAssociationRecord> getPrimaryKey() {
        return Keys.KEY_CORRELATION_DASHBOARD_ASSOCIATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CorrelationDashboardAssociationRecord>> getKeys() {
        return Arrays.<UniqueKey<CorrelationDashboardAssociationRecord>>asList(Keys.KEY_CORRELATION_DASHBOARD_ASSOCIATION_PRIMARY, Keys.KEY_CORRELATION_DASHBOARD_ASSOCIATION_UNIQUE_KEY_ON_CORRELATION_ID_AND_USER_DASHBOARD_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CorrelationDashboardAssociationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CorrelationDashboardAssociationRecord, ?>>asList(Keys.FK_CORRELATION_DASHBOARD_ASSOCIATION_CORRELATION_ID, Keys.FK_CORRELATION_DASHBOARD_ASSOCIATION_USER_DASHBOARD_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CorrelationDashboardAssociation as(String alias) {
        return new CorrelationDashboardAssociation(alias, this);
    }

    /**
     * Rename this table
     */
    public CorrelationDashboardAssociation rename(String name) {
        return new CorrelationDashboardAssociation(name, null);
    }
}
