/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.kaddiya.reporting.sql.commons.Keys;
import org.kaddiya.reporting.sql.commons.Proof;
import org.kaddiya.reporting.sql.commons.enums.DataSetTimePeriodStepTimeseriesInterval;
import org.kaddiya.reporting.sql.commons.tables.records.DataSetTimePeriodStepRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataSetTimePeriodStep extends TableImpl<DataSetTimePeriodStepRecord> {

    private static final long serialVersionUID = 1529264050;

    /**
     * The reference instance of <code>proof.data_set_time_period_step</code>
     */
    public static final DataSetTimePeriodStep DATA_SET_TIME_PERIOD_STEP = new DataSetTimePeriodStep();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DataSetTimePeriodStepRecord> getRecordType() {
        return DataSetTimePeriodStepRecord.class;
    }

    /**
     * The column <code>proof.data_set_time_period_step.DATA_SET_TIME_PERIOD_STEP_ID</code>.
     */
    public final TableField<DataSetTimePeriodStepRecord, Integer> DATA_SET_TIME_PERIOD_STEP_ID = createField("DATA_SET_TIME_PERIOD_STEP_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.data_set_time_period_step.NAME</code>.
     */
    public final TableField<DataSetTimePeriodStepRecord, String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>proof.data_set_time_period_step.START_DATE</code>.
     */
    public final TableField<DataSetTimePeriodStepRecord, Timestamp> START_DATE = createField("START_DATE", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>proof.data_set_time_period_step.END_DATE</code>.
     */
    public final TableField<DataSetTimePeriodStepRecord, Timestamp> END_DATE = createField("END_DATE", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>proof.data_set_time_period_step.TIMESERIES_INTERVAL</code>.
     */
    public final TableField<DataSetTimePeriodStepRecord, DataSetTimePeriodStepTimeseriesInterval> TIMESERIES_INTERVAL = createField("TIMESERIES_INTERVAL", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(org.kaddiya.reporting.sql.commons.enums.DataSetTimePeriodStepTimeseriesInterval.class), this, "");

    /**
     * Create a <code>proof.data_set_time_period_step</code> table reference
     */
    public DataSetTimePeriodStep() {
        this("data_set_time_period_step", null);
    }

    /**
     * Create an aliased <code>proof.data_set_time_period_step</code> table reference
     */
    public DataSetTimePeriodStep(String alias) {
        this(alias, DATA_SET_TIME_PERIOD_STEP);
    }

    private DataSetTimePeriodStep(String alias, Table<DataSetTimePeriodStepRecord> aliased) {
        this(alias, aliased, null);
    }

    private DataSetTimePeriodStep(String alias, Table<DataSetTimePeriodStepRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Proof.PROOF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DataSetTimePeriodStepRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DATA_SET_TIME_PERIOD_STEP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DataSetTimePeriodStepRecord> getPrimaryKey() {
        return Keys.KEY_DATA_SET_TIME_PERIOD_STEP_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DataSetTimePeriodStepRecord>> getKeys() {
        return Arrays.<UniqueKey<DataSetTimePeriodStepRecord>>asList(Keys.KEY_DATA_SET_TIME_PERIOD_STEP_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DataSetTimePeriodStep as(String alias) {
        return new DataSetTimePeriodStep(alias, this);
    }

    /**
     * Rename this table
     */
    public DataSetTimePeriodStep rename(String name) {
        return new DataSetTimePeriodStep(name, null);
    }
}
