/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.kaddiya.reporting.sql.commons.Keys;
import org.kaddiya.reporting.sql.commons.Proof;
import org.kaddiya.reporting.sql.commons.tables.records.KpiDataRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class KpiData extends TableImpl<KpiDataRecord> {

    private static final long serialVersionUID = 167906405;

    /**
     * The reference instance of <code>proof.kpi_data</code>
     */
    public static final KpiData KPI_DATA = new KpiData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<KpiDataRecord> getRecordType() {
        return KpiDataRecord.class;
    }

    /**
     * The column <code>proof.kpi_data.KPI_DATA_ID</code>.
     */
    public final TableField<KpiDataRecord, Integer> KPI_DATA_ID = createField("KPI_DATA_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.kpi_data.KPI_ID</code>.
     */
    public final TableField<KpiDataRecord, Integer> KPI_ID = createField("KPI_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.kpi_data.DATA_SET_TIME_PERIOD_STEP_ID</code>.
     */
    public final TableField<KpiDataRecord, Integer> DATA_SET_TIME_PERIOD_STEP_ID = createField("DATA_SET_TIME_PERIOD_STEP_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.kpi_data.KPI_VALUE</code>.
     */
    public final TableField<KpiDataRecord, Double> KPI_VALUE = createField("KPI_VALUE", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>proof.kpi_data</code> table reference
     */
    public KpiData() {
        this("kpi_data", null);
    }

    /**
     * Create an aliased <code>proof.kpi_data</code> table reference
     */
    public KpiData(String alias) {
        this(alias, KPI_DATA);
    }

    private KpiData(String alias, Table<KpiDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private KpiData(String alias, Table<KpiDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Proof.PROOF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<KpiDataRecord, Integer> getIdentity() {
        return Keys.IDENTITY_KPI_DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<KpiDataRecord> getPrimaryKey() {
        return Keys.KEY_KPI_DATA_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<KpiDataRecord>> getKeys() {
        return Arrays.<UniqueKey<KpiDataRecord>>asList(Keys.KEY_KPI_DATA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<KpiDataRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<KpiDataRecord, ?>>asList(Keys.FK_KPI_ID, Keys.FK_DATA_SET_TIME_PERIOD_STEP_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public KpiData as(String alias) {
        return new KpiData(alias, this);
    }

    /**
     * Rename this table
     */
    public KpiData rename(String name) {
        return new KpiData(name, null);
    }
}
