/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.kaddiya.reporting.sql.commons.Keys;
import org.kaddiya.reporting.sql.commons.Proof;
import org.kaddiya.reporting.sql.commons.tables.records.OrgCategoryRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgCategory extends TableImpl<OrgCategoryRecord> {

    private static final long serialVersionUID = 1792162100;

    /**
     * The reference instance of <code>proof.org_category</code>
     */
    public static final OrgCategory ORG_CATEGORY = new OrgCategory();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgCategoryRecord> getRecordType() {
        return OrgCategoryRecord.class;
    }

    /**
     * The column <code>proof.org_category.ORG_CATEGORY_ID</code>.
     */
    public final TableField<OrgCategoryRecord, Integer> ORG_CATEGORY_ID = createField("ORG_CATEGORY_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.org_category.ORGANISATION_ID</code>.
     */
    public final TableField<OrgCategoryRecord, Integer> ORGANISATION_ID = createField("ORGANISATION_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.org_category.CATEGORY_ID</code>.
     */
    public final TableField<OrgCategoryRecord, Integer> CATEGORY_ID = createField("CATEGORY_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>proof.org_category</code> table reference
     */
    public OrgCategory() {
        this("org_category", null);
    }

    /**
     * Create an aliased <code>proof.org_category</code> table reference
     */
    public OrgCategory(String alias) {
        this(alias, ORG_CATEGORY);
    }

    private OrgCategory(String alias, Table<OrgCategoryRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrgCategory(String alias, Table<OrgCategoryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Proof.PROOF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OrgCategoryRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ORG_CATEGORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrgCategoryRecord> getPrimaryKey() {
        return Keys.KEY_ORG_CATEGORY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrgCategoryRecord>> getKeys() {
        return Arrays.<UniqueKey<OrgCategoryRecord>>asList(Keys.KEY_ORG_CATEGORY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OrgCategoryRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrgCategoryRecord, ?>>asList(Keys.FK_ORG_CATEGORY_ORGANISATION_ID, Keys.FK_ORG_CATEGORY_CATEGORY_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgCategory as(String alias) {
        return new OrgCategory(alias, this);
    }

    /**
     * Rename this table
     */
    public OrgCategory rename(String name) {
        return new OrgCategory(name, null);
    }
}
