/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.kaddiya.reporting.sql.commons.Keys;
import org.kaddiya.reporting.sql.commons.Proof;
import org.kaddiya.reporting.sql.commons.tables.records.OrgCalculationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgCalculation extends TableImpl<OrgCalculationRecord> {

    private static final long serialVersionUID = -163729491;

    /**
     * The reference instance of <code>proof.org_calculation</code>
     */
    public static final OrgCalculation ORG_CALCULATION = new OrgCalculation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgCalculationRecord> getRecordType() {
        return OrgCalculationRecord.class;
    }

    /**
     * The column <code>proof.org_calculation.ORG_CALCULATION_ID</code>.
     */
    public final TableField<OrgCalculationRecord, Integer> ORG_CALCULATION_ID = createField("ORG_CALCULATION_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.org_calculation.ORGANISATION_ID</code>.
     */
    public final TableField<OrgCalculationRecord, Integer> ORGANISATION_ID = createField("ORGANISATION_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.org_calculation.CALCULATION_ID</code>.
     */
    public final TableField<OrgCalculationRecord, Integer> CALCULATION_ID = createField("CALCULATION_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>proof.org_calculation</code> table reference
     */
    public OrgCalculation() {
        this("org_calculation", null);
    }

    /**
     * Create an aliased <code>proof.org_calculation</code> table reference
     */
    public OrgCalculation(String alias) {
        this(alias, ORG_CALCULATION);
    }

    private OrgCalculation(String alias, Table<OrgCalculationRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrgCalculation(String alias, Table<OrgCalculationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Proof.PROOF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OrgCalculationRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ORG_CALCULATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrgCalculationRecord> getPrimaryKey() {
        return Keys.KEY_ORG_CALCULATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrgCalculationRecord>> getKeys() {
        return Arrays.<UniqueKey<OrgCalculationRecord>>asList(Keys.KEY_ORG_CALCULATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OrgCalculationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrgCalculationRecord, ?>>asList(Keys.FK_ORG_CALCULATION_ORGANISATION_ID, Keys.FK_ORG_CALCULATION_CALCULATION_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgCalculation as(String alias) {
        return new OrgCalculation(alias, this);
    }

    /**
     * Rename this table
     */
    public OrgCalculation rename(String name) {
        return new OrgCalculation(name, null);
    }
}
