/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.kaddiya.reporting.sql.commons.Keys;
import org.kaddiya.reporting.sql.commons.Proof;
import org.kaddiya.reporting.sql.commons.tables.records.OrgKpiRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgKpi extends TableImpl<OrgKpiRecord> {

    private static final long serialVersionUID = -179135682;

    /**
     * The reference instance of <code>proof.org_kpi</code>
     */
    public static final OrgKpi ORG_KPI = new OrgKpi();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgKpiRecord> getRecordType() {
        return OrgKpiRecord.class;
    }

    /**
     * The column <code>proof.org_kpi.ORG_KPI_ID</code>.
     */
    public final TableField<OrgKpiRecord, Integer> ORG_KPI_ID = createField("ORG_KPI_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.org_kpi.ORGANISATION_ID</code>.
     */
    public final TableField<OrgKpiRecord, Integer> ORGANISATION_ID = createField("ORGANISATION_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.org_kpi.KPI_ID</code>.
     */
    public final TableField<OrgKpiRecord, Integer> KPI_ID = createField("KPI_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>proof.org_kpi</code> table reference
     */
    public OrgKpi() {
        this("org_kpi", null);
    }

    /**
     * Create an aliased <code>proof.org_kpi</code> table reference
     */
    public OrgKpi(String alias) {
        this(alias, ORG_KPI);
    }

    private OrgKpi(String alias, Table<OrgKpiRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrgKpi(String alias, Table<OrgKpiRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Proof.PROOF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OrgKpiRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ORG_KPI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrgKpiRecord> getPrimaryKey() {
        return Keys.KEY_ORG_KPI_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrgKpiRecord>> getKeys() {
        return Arrays.<UniqueKey<OrgKpiRecord>>asList(Keys.KEY_ORG_KPI_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OrgKpiRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrgKpiRecord, ?>>asList(Keys.FK_ORG_KPI_ORGANISATION_ID, Keys.FK_ORG_KPI_KPI_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgKpi as(String alias) {
        return new OrgKpi(alias, this);
    }

    /**
     * Rename this table
     */
    public OrgKpi rename(String name) {
        return new OrgKpi(name, null);
    }
}
