/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.kaddiya.reporting.sql.commons.Keys;
import org.kaddiya.reporting.sql.commons.Proof;
import org.kaddiya.reporting.sql.commons.tables.records.OrgKpiCombinationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgKpiCombination extends TableImpl<OrgKpiCombinationRecord> {

    private static final long serialVersionUID = 1107219082;

    /**
     * The reference instance of <code>proof.org_kpi_combination</code>
     */
    public static final OrgKpiCombination ORG_KPI_COMBINATION = new OrgKpiCombination();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgKpiCombinationRecord> getRecordType() {
        return OrgKpiCombinationRecord.class;
    }

    /**
     * The column <code>proof.org_kpi_combination.ORG_KPI_COMBINATION_ID</code>.
     */
    public final TableField<OrgKpiCombinationRecord, Integer> ORG_KPI_COMBINATION_ID = createField("ORG_KPI_COMBINATION_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.org_kpi_combination.ORGANISATION_ID</code>.
     */
    public final TableField<OrgKpiCombinationRecord, Integer> ORGANISATION_ID = createField("ORGANISATION_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.org_kpi_combination.KPI_COMBINATION_ID</code>.
     */
    public final TableField<OrgKpiCombinationRecord, Integer> KPI_COMBINATION_ID = createField("KPI_COMBINATION_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>proof.org_kpi_combination</code> table reference
     */
    public OrgKpiCombination() {
        this("org_kpi_combination", null);
    }

    /**
     * Create an aliased <code>proof.org_kpi_combination</code> table reference
     */
    public OrgKpiCombination(String alias) {
        this(alias, ORG_KPI_COMBINATION);
    }

    private OrgKpiCombination(String alias, Table<OrgKpiCombinationRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrgKpiCombination(String alias, Table<OrgKpiCombinationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Proof.PROOF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OrgKpiCombinationRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ORG_KPI_COMBINATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrgKpiCombinationRecord> getPrimaryKey() {
        return Keys.KEY_ORG_KPI_COMBINATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrgKpiCombinationRecord>> getKeys() {
        return Arrays.<UniqueKey<OrgKpiCombinationRecord>>asList(Keys.KEY_ORG_KPI_COMBINATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OrgKpiCombinationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrgKpiCombinationRecord, ?>>asList(Keys.FK_ORG_KPI_COMBINATION_ORGANISATION_ID, Keys.FK_ORG_KPI_COMBINATION_KPI_COMBINATION_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgKpiCombination as(String alias) {
        return new OrgKpiCombination(alias, this);
    }

    /**
     * Rename this table
     */
    public OrgKpiCombination rename(String name) {
        return new OrgKpiCombination(name, null);
    }
}
