/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.kaddiya.reporting.sql.commons.Keys;
import org.kaddiya.reporting.sql.commons.Proof;
import org.kaddiya.reporting.sql.commons.enums.OrgPlanStatus;
import org.kaddiya.reporting.sql.commons.tables.records.OrgPlanRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgPlan extends TableImpl<OrgPlanRecord> {

    private static final long serialVersionUID = -859944390;

    /**
     * The reference instance of <code>proof.org_plan</code>
     */
    public static final OrgPlan ORG_PLAN = new OrgPlan();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgPlanRecord> getRecordType() {
        return OrgPlanRecord.class;
    }

    /**
     * The column <code>proof.org_plan.ORG_PLAN_ID</code>.
     */
    public final TableField<OrgPlanRecord, Integer> ORG_PLAN_ID = createField("ORG_PLAN_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.org_plan.ORGANISATION_ID</code>.
     */
    public final TableField<OrgPlanRecord, Integer> ORGANISATION_ID = createField("ORGANISATION_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.org_plan.SUBSCRIPTION_PLAN_ID</code>.
     */
    public final TableField<OrgPlanRecord, Integer> SUBSCRIPTION_PLAN_ID = createField("SUBSCRIPTION_PLAN_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.org_plan.STATUS</code>.
     */
    public final TableField<OrgPlanRecord, OrgPlanStatus> STATUS = createField("STATUS", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(org.kaddiya.reporting.sql.commons.enums.OrgPlanStatus.class), this, "");

    /**
     * Create a <code>proof.org_plan</code> table reference
     */
    public OrgPlan() {
        this("org_plan", null);
    }

    /**
     * Create an aliased <code>proof.org_plan</code> table reference
     */
    public OrgPlan(String alias) {
        this(alias, ORG_PLAN);
    }

    private OrgPlan(String alias, Table<OrgPlanRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrgPlan(String alias, Table<OrgPlanRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Proof.PROOF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OrgPlanRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ORG_PLAN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrgPlanRecord> getPrimaryKey() {
        return Keys.KEY_ORG_PLAN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrgPlanRecord>> getKeys() {
        return Arrays.<UniqueKey<OrgPlanRecord>>asList(Keys.KEY_ORG_PLAN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OrgPlanRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrgPlanRecord, ?>>asList(Keys.FK_ORG_PLAN_ORGANISATION_ID, Keys.FK_ORG_PLAN_SUBSCRIPTION_PLAN_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgPlan as(String alias) {
        return new OrgPlan(alias, this);
    }

    /**
     * Rename this table
     */
    public OrgPlan rename(String name) {
        return new OrgPlan(name, null);
    }
}
