/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.kaddiya.reporting.sql.commons.Keys;
import org.kaddiya.reporting.sql.commons.Proof;
import org.kaddiya.reporting.sql.commons.tables.records.OrgUserDashboardRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgUserDashboard extends TableImpl<OrgUserDashboardRecord> {

    private static final long serialVersionUID = 536253060;

    /**
     * The reference instance of <code>proof.org_user_dashboard</code>
     */
    public static final OrgUserDashboard ORG_USER_DASHBOARD = new OrgUserDashboard();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgUserDashboardRecord> getRecordType() {
        return OrgUserDashboardRecord.class;
    }

    /**
     * The column <code>proof.org_user_dashboard.ORG_USER_DASHBOARD_ID</code>.
     */
    public final TableField<OrgUserDashboardRecord, Integer> ORG_USER_DASHBOARD_ID = createField("ORG_USER_DASHBOARD_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.org_user_dashboard.ORGANISATION_ID</code>.
     */
    public final TableField<OrgUserDashboardRecord, Integer> ORGANISATION_ID = createField("ORGANISATION_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.org_user_dashboard.USER_DASHBOARD_ID</code>.
     */
    public final TableField<OrgUserDashboardRecord, Integer> USER_DASHBOARD_ID = createField("USER_DASHBOARD_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>proof.org_user_dashboard</code> table reference
     */
    public OrgUserDashboard() {
        this("org_user_dashboard", null);
    }

    /**
     * Create an aliased <code>proof.org_user_dashboard</code> table reference
     */
    public OrgUserDashboard(String alias) {
        this(alias, ORG_USER_DASHBOARD);
    }

    private OrgUserDashboard(String alias, Table<OrgUserDashboardRecord> aliased) {
        this(alias, aliased, null);
    }

    private OrgUserDashboard(String alias, Table<OrgUserDashboardRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Proof.PROOF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OrgUserDashboardRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ORG_USER_DASHBOARD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrgUserDashboardRecord> getPrimaryKey() {
        return Keys.KEY_ORG_USER_DASHBOARD_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrgUserDashboardRecord>> getKeys() {
        return Arrays.<UniqueKey<OrgUserDashboardRecord>>asList(Keys.KEY_ORG_USER_DASHBOARD_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<OrgUserDashboardRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<OrgUserDashboardRecord, ?>>asList(Keys.FK_ORG_DASHBOARD_ORGANISATION_ID, Keys.FK_ORG_DASHBOARD_USER_DASHBOARD_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgUserDashboard as(String alias) {
        return new OrgUserDashboard(alias, this);
    }

    /**
     * Rename this table
     */
    public OrgUserDashboard rename(String name) {
        return new OrgUserDashboard(name, null);
    }
}
