/**
 * This class is generated by jOOQ
 */
package org.kaddiya.reporting.sql.commons.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;
import org.kaddiya.reporting.sql.commons.Keys;
import org.kaddiya.reporting.sql.commons.Proof;
import org.kaddiya.reporting.sql.commons.enums.VceOrientationOrientationType;
import org.kaddiya.reporting.sql.commons.tables.records.VceOrientationRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VceOrientation extends TableImpl<VceOrientationRecord> {

    private static final long serialVersionUID = 1449977922;

    /**
     * The reference instance of <code>proof.vce_orientation</code>
     */
    public static final VceOrientation VCE_ORIENTATION = new VceOrientation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VceOrientationRecord> getRecordType() {
        return VceOrientationRecord.class;
    }

    /**
     * The column <code>proof.vce_orientation.VCE_ORIENTATION_ID</code>.
     */
    public final TableField<VceOrientationRecord, Integer> VCE_ORIENTATION_ID = createField("VCE_ORIENTATION_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.vce_orientation.VALUE_CHAIN_ID</code>.
     */
    public final TableField<VceOrientationRecord, Integer> VALUE_CHAIN_ID = createField("VALUE_CHAIN_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.vce_orientation.VALUE_CHAIN_ELEMENT_ID</code>.
     */
    public final TableField<VceOrientationRecord, Integer> VALUE_CHAIN_ELEMENT_ID = createField("VALUE_CHAIN_ELEMENT_ID", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>proof.vce_orientation.ORIENTATION_TYPE</code>.
     */
    public final TableField<VceOrientationRecord, VceOrientationOrientationType> ORIENTATION_TYPE = createField("ORIENTATION_TYPE", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(org.kaddiya.reporting.sql.commons.enums.VceOrientationOrientationType.class), this, "");

    /**
     * The column <code>proof.vce_orientation.TIME_SERIES</code>.
     */
    public final TableField<VceOrientationRecord, String> TIME_SERIES = createField("TIME_SERIES", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * The column <code>proof.vce_orientation.CORRELATION_STRENGTH</code>.
     */
    public final TableField<VceOrientationRecord, Double> CORRELATION_STRENGTH = createField("CORRELATION_STRENGTH", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * The column <code>proof.vce_orientation.TIME_TO_IMPACT</code>.
     */
    public final TableField<VceOrientationRecord, Double> TIME_TO_IMPACT = createField("TIME_TO_IMPACT", org.jooq.impl.SQLDataType.DOUBLE, this, "");

    /**
     * Create a <code>proof.vce_orientation</code> table reference
     */
    public VceOrientation() {
        this("vce_orientation", null);
    }

    /**
     * Create an aliased <code>proof.vce_orientation</code> table reference
     */
    public VceOrientation(String alias) {
        this(alias, VCE_ORIENTATION);
    }

    private VceOrientation(String alias, Table<VceOrientationRecord> aliased) {
        this(alias, aliased, null);
    }

    private VceOrientation(String alias, Table<VceOrientationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Proof.PROOF;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<VceOrientationRecord, Integer> getIdentity() {
        return Keys.IDENTITY_VCE_ORIENTATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VceOrientationRecord> getPrimaryKey() {
        return Keys.KEY_VCE_ORIENTATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VceOrientationRecord>> getKeys() {
        return Arrays.<UniqueKey<VceOrientationRecord>>asList(Keys.KEY_VCE_ORIENTATION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<VceOrientationRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<VceOrientationRecord, ?>>asList(Keys.FK_VALUE_CHAIN_ORIENTATION_CHAIN_ID, Keys.FK_VALUE_CHAIN_ELEMENT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VceOrientation as(String alias) {
        return new VceOrientation(alias, this);
    }

    /**
     * Rename this table
     */
    public VceOrientation rename(String name) {
        return new VceOrientation(name, null);
    }
}
